### ISSUE TITLE
CCM Pedido Online - Incluir mais níveis de complementos

### ISSUE THREAD

**Issue by alankoba** [Abrasel-Nacional/opendelivery#10]
Descrição de um cenário bastante comum no Brasil, e não contemplado na versão atual da documentação.

Pizza 3 sabores.
1/3 Frango
1/3 Camarão
 - Incluir cream Cheese + R$ 5,00
1/3 Portuguesa

Sei que o padrão é aberto, e posso, a meu critério incluir as informações em formato nested, assim como é no Rappi por exemplo, mas acredito que a padronização é fundamental para mantermos a interoperabilidade desde o inicio.

**Comment by gui-camargo** [comment]
Oi Alan.

Acho que a estrutura ficou formatada errada. Só pra ver se está correto:

Item: Pizza 3 Sabores:

 - Grupo de Opcional: Escolha o Sabor 1
   - Frango [x]
   - Camarão [ ] 
   - Portuguesa [ ]
   
 - Grupo de Opcional: Escolha o Sabor 2
   - Frango [ ]
   - Camarão [x]
     -  Grupo de Opcional: Escolha um Adicional
         - Cream Cheese [x]
         - Requeijão [ ]
   - Portuguesa [ ]
   
 - Grupo de Opcional: Escolha o Sabor 3
   - Frango [ ]
   - Camarão [ ] 
   - Portuguesa [x]
   
   Seria isso correto?
   
Este assunto chegou a ser discutido dentre os grupos de trabalho e comitês técnicos e definiu-se seguir com 1 nível para a versão 1.00 da documentação, mas estamos vendo que as empresas estão apontando a necessidade de mais níveis, então vamos levar novamente para discussão no próximo comitê técnico.  

Obrigado Alan.

**Comment by gui-camargo** [comment]
Após discussões no comitê do dia 05/08/2021, ficou-se definido que para a primeira versão da API do Open Delivery, se mantido apenas 1 nível de grupo de opcionais (OptionGroup) por item.

Algumas sugestões de como tratar sub-níveis foram apresentadas e podem ser utilizadas na montagem dos cardápios:

**Opção 1:**
Adicionais em um OptionGroup específico e o usuário colocando observações de como aplicar o adicional no prato:

![image](https://user-images.githubusercontent.com/80956588/129048794-0ecd9480-aae8-4f43-aef7-d8c064fe6c5f.png)

**Opção 2:**
OptionGroups específicos:

![image](https://user-images.githubusercontent.com/80956588/129049065-f0274d1d-e53a-41e8-a4ca-f4d8eaf96090.png)

De qualquer maneira, a opção de mais níveis foi registrada no Backlog do projeto, e será contemplada nas próximas versões da API.
