### ISSUE TITLE
[DeliveryVip] Pedidos Agendados

### ISSUE THREAD

**Issue by juliano-sfhera** [Abrasel-Nacional/opendelivery#100]
Estamos integrando com duas software houses que estão necessitando do agendamento de pedidos.
Por este motivo estamos criando novamente esta issue para que este assunto seja discutido.

Eu já havia aberto em setembro de 2021 a Issue [Nº17](https://github.com/Abrasel-Nacional/docs/issues/27), porém a mesma foi encerrada por falta de interação.

Acho importante darmos atenção para este ponto pois está sendo muito utilizado por todos os tipos de estabelecimento,
não só mercados como foi comentado na época que seria a maior necessidade.

**Comment by gui-camargo** [comment]
Olá @sfhera,

Como discutimos no comite a opção de pedidos agendados será contemplada na versão 1.0.1.
A documentação da versão release candidate já foi atualizada com a nova funcionalidade.
https://abrasel-nacional.github.io/docs/beta/#tag/versionChangelog

A issue ficará aberta até o release da versão 1.0.1.

**Comment by gui-camargo** [comment]
Olá @sfhera 

A versão 1.0.1 foi atualizada com as novas informações de agendamento:

 - Added the possibility to indicate orders with scheduled delivery.  
  With this the following changes were made:

    - [GET /merchant](#operation/getMerchant)
      - `service` > Added a new optional field `serviceTiming`, where the merchant can indicate the delivery timing available for that service.

      ```
      ...
      "serviceTiming":
          {
              "timing": ["INSTANT", "SCHEDULED"],
              "schedule":
                  {
                      "scheduleTimeWindow": "15_MINUTES",
                      "scheduleStartWindow": "15_MINUTES",
                      "scheduleEndWindow": "15_MINUTES",
                  },
      ...
      ```
