### ISSUE TITLE
[Qrbox] Quantidade decimal

### ISSUE THREAD

**Issue by watersonfelix** [Abrasel-Nacional/opendelivery#101]
Olhei nas issues e documentações e não encontrei nada sobre quantidade decimal.
Temos clientes no aqui no Qrbox, que vendem produtos por Kg, como padaria, podemos esperar que os Software service estão esperando receber em decimal ou não, visto que os campos geralmente tem identificação quando é decimal, e justo na quantidade dos itens está só number sem o <decimal> ?

**Comment by gui-camargo** [comment]
Olá @watersonfelix,

Pelo schema do Json, o type 'number' aceita decimais, então na teoria todos os campos que são 'number' podem aceitar decimais. 
Os campos que estão especificamente como decimais no format, são campos que precisamos especificar o numero de casas. 

Além da quantidade, é necessário se atentar ao campo unit, indicando corretamente a unidade de medida do item.

De qualquer maneira vamos debater esse assunto no comite do dia 07/07/2022 para ver se precisamos colocar alguma recomendação na documentação.

**Comment by gui-camargo** [comment]
Olá @watersonfelix,

Os campos foram atualizados na versão 1.0.1 indicando o format correto para os campos do tipo 'number'.

Documentação já disponível.
