### ISSUE TITLE
[DeliveryVip] Confirmação do pedido

### ISSUE THREAD

**Issue by danieldocki** [Abrasel-Nacional/opendelivery#102]
Quando acontece a confirmação do pedido no

`POST /confirm`

e por algum engano é enviado novamente esse request

`POST /confirm`

Temos que aceitar essa confirmação ou retornar um erro?

No meu caso estou retornando que não aceitei o evento porque já foi confirmado o pedido.

**Comment by filipesarturi** [comment]
Acredito que o tratamento de requisições duplicadas deve ser feito tanto no lado do cliente (por ex: desabilitar o botão até obter uma resposta da requisição...) quanto do servidor (identificar que aquele pedido já foi confirmado), neste último caso acho que é mais vantajoso não retornar erro e sim um status 202 com algum dado no corpo identificando que já foi confirmado (talvez data/hora da confirmação), assim evita mensagens de erro do lado do cliente sendo que o pedido já foi confirmado.

**Comment by gui-camargo** [comment]
Olá @danieldocki 
Como o @filipesarturi falou, fica a cargo das partes o tratamento de duplicidades. Mas podemos conversar no comite se podemos adotar alguma recomendação como padrão, ou até colocar algum código mais especifico, como o HTTP 409 Conflict por exemplo.

**Comment by danieldocki** [comment]
Hoje estou retornando 422 quando um pedido já foi confirmado.

**Comment by gui-camargo** [comment]
Olá @danieldocki 

Adicionamos o HTTP code 422 nos endpoints dos eventos do pedido.

Já disponível na versão 1.0.1.
