### ISSUE TITLE
[Delivery In Box] Sugestão de melhoria em retornos sem conteúdo

### ISSUE THREAD

**Issue by filipesarturi** [Abrasel-Nacional/opendelivery#103]
Certas rotas não retornam nenhum dado e utilizam o status 200, acredito que nesses casos o código mais apropriado seria o 204 (No Content) pois indica sucesso e sem dado no corpo da resposta, também força certos clientes a interromper o processamento após a leitura do cabeçalho.

Algumas rotas que notei esse caso:

- **POST** /v1/merchantUpdate
- **POST** /v1/orders/{orderId}/acceptCancellation
- **POST** /v1/orders/{orderId}/denyCancellation

**Comment by gui-camargo** [comment]
Olá filipe.

Vamos discutir essa questão no próximo comite técnico (dia 07/07/2022).

**Comment by gui-camargo** [comment]
Olá @filipesarturi 

Adicionamos o HTTP code 204 nos endpoints que não possuem body de retorno.

Já disponível na versão 1.0.1.

Obs: O HTTP code 200 foi mantido por questões de compatibilidade.
