### ISSUE TITLE
[Epadoca] Dúvida sobre configuração de webhook

### ISSUE THREAD

**Issue by flastowizka** [Abrasel-Nacional/opendelivery#104]
1. Relacionado ao Abrasel-Nacional/docs#94 , existe alguma especificação para definir se aquele merchant irá trabalhar com webhook ou polling? Pensando em não ter inconsistência de dados, não faz muito sentido o merchant trabalhar com polling + webhook.
2. Como configura para o merchant os endpoints de webhook que o Marketplace irá chamar nas atualizações? (Não consegui localizar na documentação, pode ser que até tenha)

**Comment by gui-camargo** [comment]
Bom dia @flastowizka 

Esclarecendo as dúvidas:

1 - A ideia realmente é que o merchant trabalhe com um ou outro. Essa definição de como o software vai trabalhar com o aplicativo, vai ficar a cargo do onboarding entre os dois. Hoje não temos uma forma de definir isso via API.

2 - Também hoje não temos um endpoint para definir a rota. Essa configuração precisaria ser passada externamente para o aplicativo/marketplace.

De qualquer maneira vamos levar essas questões para o próximo comite, e ver se conseguimos evoluir de alguma maneira a API para facilitar essas comunicações.

**Comment by flastowizka** [comment]
> Bom dia @flastowizka
> 
> Esclarecendo as dúvidas:
> 
> 1 - A ideia realmente é que o merchant trabalhe com um ou outro. Essa definição de como o software vai trabalhar com o aplicativo, vai ficar a cargo do onboarding entre os dois. Hoje não temos uma forma de definir isso via API.
> 
> 2 - Também hoje não temos um endpoint para definir a rota. Essa configuração precisaria ser passada externamente para o aplicativo/marketplace.
> 
> De qualquer maneira vamos levar essas questões para o próximo comite, e ver se conseguimos evoluir de alguma maneira a API para facilitar essas comunicações.

Obrigado pelos esclarecimentos @gui-camargo

**Comment by gui-camargo** [comment]
Olá @flastowizka,

Colocamos alguns novos campos na versão 1.0.1 para ajudar na troca de informações do webhook:

No endpoint : `GET /v1/versions/orderingApp` colocamos o campo: `order > availableEventsMethods` para que o Originador de Pedido indique quais metodos ele trabalha (POLLING, WEBHOOK ou os dois).

No endpoint: `PUT /v1/merchantOnboarding` colocamos o campo: `ordersWebhookURL` para que o merchant indique qual a URL do webhook para receber os eventos do pedido.

Obrigado pela sugestão.
