### ISSUE TITLE
[e-Deploy] - Autenticação nas APIs de Logística

### ISSUE THREAD

**Issue by eduardoalmeida** [Abrasel-Nacional/opendelivery#105]
Na documentação existe apenas a menção de que as APIs utilizam Oauth2. 
A API de Autenticação está dentro da parte de Pedido e Cardápio.
Acredito que faz sentido ser a mesma API, talvez tirar ela de dentro do Pedido e Cardápio.
O client_id / client_secret será por merchant igual o Pedido/Cardápio?
No pedido cardápio foi levantado a impossibilidade do Software Service se autenticar no Ordering Application, faz sentido tratarmos isso na Logística?

**Comment by OpenDelivery-Tech** [comment]
@eduardoalmeida,

Conforme falado em comitê, melhoramos o texto da parte de segurança para ficar claro que o oAuth2 deve ser usado tanto pelos Ordering Application como pelos Logistics Service.

Estará disponível na próxima versão. Assim que o merge for feito fechamos a issue.

**Comment by OpenDelivery-Tech** [comment]
Olá @eduardoalmeida 

O texto da autenticação foi revisado e já está disponível na versão v1.4.0 da API.

Changelog:

```
- Changed the text describing OAuth2 authentication, making clear the roles of the Ordering Application and the
 Logistics Service, since they both use the same logic to provide the access credentials and the token URL.
```

A issue será fechada.
