### ISSUE TITLE
[Inter] Ajuste no paymentBatchInfo do endpoint Get Contract Conditions for Merchant

### ISSUE THREAD

**Issue by robertoroque-inter** [Abrasel-Nacional/opendelivery#106]
No response do endpoint /v1/signup/contractConditions, no retorno do paymentBacthInfo há a informação do período, que pode ser diário ou por período. No caso dos repasses por período, como no caso do Inter, podem ser mais de um período no mesmo modelo de repasse. Por exemplo: repassamos todos os dias 01 e 16 de cada mês, correspondentes aos 30 dias anteriores de cada período. Idealmente, precisamos ajustar o campo period para um array of objects ao invés de apenas um objeto.

<img width="592" alt="image" src="https://user-images.githubusercontent.com/108092397/175376396-7b178ab1-86e5-4b0a-9c3a-2d132f66a8e6.png">

**Comment by gui-camargo** [comment]
Olá @robertoroque-inter 

Vamos discutir a issue no próximo comite.

**Comment by gui-camargo** [comment]
Olá @robertoroque-inter,

Esta issue acabou ficando aberta, mas a correção já está disponível na documentação.

![image](https://user-images.githubusercontent.com/80956588/199074337-ee75cf01-8825-4e0a-89a8-0f2bfa80847a.png)

Estou fechando a issue. Qualquer dúvida pode reabri-la.
