### ISSUE TITLE
[TOTVS]  Inclusão do eventType no objeto Order Details

### ISSUE THREAD

**Issue by domeneghetti** [Abrasel-Nacional/opendelivery#108]
Olá, com base na versão da API (1.0.1),  quando recuperamos um evento hoje através do pooling, temos no corpo do evento a propriedade eventType, que reflete o status do pedido naquele momento

![eventType](https://user-images.githubusercontent.com/17864531/193635089-9b9ce903-bc8c-4691-bae8-8a0afafab145.png)

Porém os nossos sistemas de delivery não fazem mais a captação dos eventos / pedidos diretamente, temos um serviço que centraliza esse processo e faz essa tarefa, distribuindo apenas os pedidos já captados aos sistemas que utilizam o mesmo como uma forma de entrada de pedido.

Porém analisando o body do pedido, o mesmo não possui a informação em qual status que ele está:
![orderBody](https://user-images.githubusercontent.com/17864531/193635570-5848c778-ea70-4af1-88c8-811fef4ed8f1.png)

Isso faz com que o sistema ao receber um pedido, possua dificuldades para gerenciar \ tomar uma decisão sobre o pedido, já que, precisaria saber o status que o mesmo se encontra para isso, lembrando que os sistemas que recebem o pedido captado não conhecem o evento que precedeu o mesmo

**Comment by gui-camargo** [comment]
Olá @domeneghetti 

Conforme conversado no comite, a sugestão foi acatada e foi adicionado uma nova propriedade chamada `lastEvent` na resposta do HTTP 200.

![image](https://user-images.githubusercontent.com/80956588/199077783-9e1c733c-6823-4dfe-8b72-2f45db2dfcf0.png)

Já está disponível na versão 1.1.0 release candidate, e a issue ficará aberta até o merge com a release.

**Comment by gui-camargo** [comment]
Olá @domeneghetti, 

A alteração já está disponível na versão release.

Changelog:

>[GET /v1/orders/{orderId}](#operation/ordersDetails)
>- added new field `lastEvent` to be filled with the last valid event sent/polled (whether acknowledged or not).

A issue será fechada.
