### ISSUE TITLE
[Inter]  Financial Reports - Get Payments Batches by Id

### ISSUE THREAD

**Issue by Kerley32** [Abrasel-Nacional/opendelivery#109]
No retorno da consulta de lotes de pagamento por ID, o campo `ordersChargebacks.amount` está como string, acredito que deveria ser um objeto Price.

**Comment by gui-camargo** [comment]
Olá @Kerley32,

A alteração foi efetuada e já está disponível na documentação.

![image](https://user-images.githubusercontent.com/80956588/199074002-af0ec53e-31ef-4d41-868e-6ab76c1d8ccf.png)

Issue será fechada.
