### ISSUE TITLE
[e-Deploy] - Possibilidade de cardápios distintos por sourceAppId

### ISSUE THREAD

**Issue by eduardoalmeida** [Abrasel-Nacional/opendelivery#11]
Atualmente, em uma integração entre um PDV e um Hub de Delivery não é possível ter cardápios diferentes por marketplace que é atendido pelo Hub de Delivery.
Um Hub de Delivery pode concentrar pedidos de mais de um Marketplace e disponibilizá-los através da integração de pedidos para o PDV, mas não é possível o PDV informar cardápios diferentes para Marketplaces diferentes.
A sugestão seria colocar um campo opicional sourceAppId na entidade Service. Dessa maneira o Hub de Delivery poderia disponibilizar a lista de sourceAppIds atendidos e o PDV poderia informar cardápios diferentes para cada um deles.

**Comment by gui-camargo** [comment]
Olá @eduardoalmeida,

Conforme conversamos no comite, vamos adicionar o campo sourceAppId na entidade Service na próxima versão da API.

**Comment by gui-camargo** [comment]
Olá @eduardoalmeida 

A alteração já está disponível na versão release.

Changelog:
> [GET /v1/merchant](#operation/getMerchant)
>- added new optional field `targetAppId` in the `service` entity of endpoint [GET /v1/merchant](#operation/getMerchant).
>This field is intended to indicate a specific Ordering Application to receive the service information.

A issue será fechada.
