### ISSUE TITLE
[Inter] Financial Reports - Get Payments Batches by Dates

### ISSUE THREAD

**Issue by Kerley32** [Abrasel-Nacional/opendelivery#110]
No retorno da consulta de lotes de pagamento por data é retornado uma lista de objetos com um summary e um batches cada.

Como o campo `summary` já retorna o total, a quantidade de registros que faltam e o período será o período filtrado, não deveríamos manter apenas um `summary` e retornar uma lista de `batches`?

**Comment by gui-camargo** [comment]
Olá @Kerley32,

A correção do endpoint foi efetuada e já está disponível na documentação.

![image](https://user-images.githubusercontent.com/80956588/199078273-e270cad8-8a15-4ece-bac1-8c171518652e.png)
 
 A issue será fechada mas qualquer dúvida pode reabri-la.
