### ISSUE TITLE
[Inter] Padronização de campos de logística versão Beta

### ISSUE THREAD

**Issue by cesarcorreiainter** [Abrasel-Nacional/opendelivery#111]
No payload de deliveryUpdate sugiro a seguinte padronização de atributos:

- rejectionInfo.reason[DOES_NOT_MEET_REQUETED_TIMES].metadata.pickupEtaMinutes para pickupEtaInMinutes
- rejectionInfo.reason[DOES_NOT_MEET_REQUETED_TIMES].metadata.deliveryEtainMinutes para deliveryEtaInMinutes (I do In em maiúsculo)
- eta.pickupEtaMinutes para pickupEtaInMinutes
- eta.deliveryEtainMinutes para deliveryEtaInMinutes (I do In em maiúsculo)

**Comment by gui-camargo** [comment]
Olá @cesarcorreiainter,

Vamos levar o assunto para o comite desta quinta.

**Comment by gui-camargo** [comment]
Olá @cesarcorreiainter,

Conforme discutido no comite, as alterações foram acatadas e já estão disponíveis na versão beta da documentação.

https://abrasel-nacional.github.io/docs/versions/beta/#section/Changelog

Issue será fechada.
