### ISSUE TITLE
[Inter] Inclusão de informação dos cartões aceitos pelo Merchant

### ISSUE THREAD

**Issue by cesarcorreiainter** [Abrasel-Nacional/opendelivery#112]
Sugiro a inclusão das bandeiras de cartões que o Merchant aceita no payload do mesmo. Sugestão, incluir em MerchantBasicInfo, como um array.  A necessidade para o Ordering Application é especificamente saber quais os vouchers que o restaurante está aceitando no momento, já que o pagamento de vouchers quando realizado na wallet de pagamento do Ordering Application precisa desta informação para liberação. Mesmo que na wallet tenhamos já a informação de chave do merchant para pagamento e quais bandeiras o merchant aceita acredito que se, o merchant quiser, temporariamente, suspender os pagamentos feitos através da algum voucher de maneira indireta, sem quebra de contrato, para negociar novamente taxas, etc, ele poderia efetuar este bloqueio no Software Service que enviaria a alteração de dados para o Ordering Application.

**Comment by gui-camargo** [comment]
Olá @cesarcorreiainter,

Vamos levar o assunto para o comite desta quinta.

**Comment by gui-camargo** [comment]
Olá @cesarcorreiainter,

Conforme conversamos no comite, o campo acceptedCards foi incluido no merchant.basicInfo.

Já está disponível na versão release candidate (rc.6).

Changelog:
- added new optional propertie `acceptedCards` in the `basicInfo` entity of endpoint [GET /v1/merchant](https://abrasel-nacional.github.io/docs/versions/rc/#tag/merchantEndpoints/operation/getMerchant).

  This field is intended to indicate which card brands are accepted by the merchant.

**Comment by gui-camargo** [comment]
Olá @cesarcorreiainter,

A alteração já está disponível na versão release.

Changelog:

> [GET /v1/merchant](#operation/getMerchant)
> - added new optional propertie `acceptedCards` in the `basicInfo` entity of endpoint.
> This field is intended to indicate which card brands are accepted by the merchant.

A issue será fechada.
