### ISSUE TITLE
[e-Deploy] Logistic - WebHook - Campos required e evento "REJECTED"

### ISSUE THREAD

**Issue by eduardoalmeida** [Abrasel-Nacional/opendelivery#113]
Atualmente os campos

- vehicle
- deliveryPrice
- eta
- deliveryMan

estão como "required" no WebHook mas eles não fazem sentido para o evento de REJECTED.

Se tirar o required, a documentação teria que ser alterada para informar que esses campos são obrigatórios para os outros eventos.
Talvez seja melhor criar objetos diferentes para cada evento.

**Comment by gui-camargo** [comment]
Olá @eduardoalmeida,

Vamos levar para discussão no comite de quinta-feira (03/11/2022).

**Comment by gui-camargo** [comment]
Olá @eduardoalmeida ,

A alteração da obrigatoriedade foi efetuada e já está disponível na documentação beta.

https://abrasel-nacional.github.io/docs/versions/beta/#section/Changelog

Issue será fechada.
