### ISSUE TITLE
[e-Deploy] - ETA no "RETURNING_TO_MERCHANT"

### ISSUE THREAD

**Issue by eduardoalmeida** [Abrasel-Nacional/opendelivery#114]
Atualmente o objeto eta possui campos para informar os tempos de pickup e de delivery. Mas não possui campos para informar o eta do entregador retornar ao estabelecimento (quando returnToMerchant for true).
A sugestão seria colocar dois campos a mais opcionais: returnToMerchantEtaInMinutes e returnToMerchantEtaDatetime. Esses campos deveriam ser obrigatórios apenas para o evento "RETURNING_TO_MERCHANT"
Uma outra opção seria colocar esses campos como obrigatórios desde o começo se o returnToMerchat fosse true.

**Comment by gui-camargo** [comment]
Olá @eduardoalmeida 

Vamos levar o assunto para o próximo comite.

**Comment by gui-camargo** [comment]
Olá @eduardoalmeida,

Conforme conversado no comite, os campos foram incluidos na documentação.

Já disponível na versão BETA.

Changelog:

- **[POST /v1/deliveryUpdate](https://abrasel-nacional.github.io/docs/versions/beta/#operation/newLogisticEvent) - Webhook Request Body**
  - added propeties `returnToMerchantEtaInMinutes` and `returnToMerchantEtaDatetime` to the `eta` object.
          
- **[POST /v1/logistics/availability](https://abrasel-nacional.github.io/docs/versions/beta/#tag/logisticPrice) - Response Body**
  - added propeties `returnToMerchantEtaInMinutes` and `returnToMerchantEtaDatetime` to the `ETAs` object.
