### ISSUE TITLE
[Epadoca] Padrão de Unit dos produtos

### ISSUE THREAD

**Issue by flastowizka** [Abrasel-Nacional/opendelivery#115]
Existe algum padrão para o campo Unit do Item?

KG
UN
GR

https://abrasel-nacional.github.io/docs/#tag/merchantStructure/Menu/Item

**Comment by gui-camargo** [comment]
Olá @flastowizka,

Inicialmente o campo seria utilizado apenas para Unidade  (UN), mas durante os grupos de trabalho, preferiram deixar o campo livre. 
Como não tivemos issues relacionada ao assunto, o campo se manteve assim.

Vou levar a discussão para o próximo comite, para entender se é o caso de criarmos um ENUM para o campo.

**Comment by flastowizka** [comment]
> Olá @flastowizka,
> 
> Inicialmente o campo seria utilizado apenas para Unidade (UN), mas durante os grupos de trabalho, preferiram deixar o campo livre. Como não tivemos issues relacionada ao assunto, o campo se manteve assim.
> 
> Vou levar a discussão para o próximo comite, para entender se é o caso de criarmos um ENUM para o campo.

Perfeito, eventualmente utilizar um ENUM com as unidades de medidas padrões... Unidade(UN), Quilograma(KG), etc

**Comment by flastowizka** [comment]
@gui-camargo segue sugestões, que atualmente usamos no nosso fluxo:

Gramas (G)
Quilo (KG)
Litro (L)
Unidade (UN)

**Comment by gui-camargo** [comment]
Olá @flastowizka,

O enum do campo unit foi inserido na documentação.

No fim, após discussão no comite, preferimos não usar unidades fracionadas (como gramas por exemplo). Então se necessário, informar a quantidade de maneira fracionada.
Exemplo: 500 gramas -> usar 0.5KG

Unidades adicionadas:
  - `UN` - Unit  
  - `KG` - Kilogram  
  - `L` - Liter
  - `OZ` - Ounce  
  - `LB` - Pound  
  - `GAL` - Gallon
  
 Já disponível na versão release candidate (rc.6).

Changelog:

#### MERCHANT changes
 - added an enumerator to propertie `unit` in the `items` entity of endpoint [GET /v1/merchant](https://abrasel-nacional.github.io/docs/versions/rc/#tag/merchantEndpoints/operation/getMerchant).

#### ORDERS changes

- added more options to the enumerator of propertie `unit` in the `items` entity of endpoint [GET /v1/orders/{orderId}](https://abrasel-nacional.github.io/docs/versions/rc/#tag/ordersDetails/operation/ordersDetails), reflecting the created enum described above.

**Comment by gui-camargo** [comment]
Olá @flastowizka, 

A alteração já está disponível na versão release.

Changelog:
>[GET /v1/merchant](#operation/getMerchant)
>- added an enumerator to propertie `unit` in the `items` entity of endpoint [GET /v1/merchant](#operation/getMerchant).

>[GET /v1/orders/{orderId}](#operation/ordersDetails)
>- added more options to the enumerator of propertie `unit` in the `items` entity of the endpoint, reflecting the created enum.

A issue será fechada.
