### ISSUE TITLE
[e-Deploy] - Webhook para SOFTWARE APPLICATION enviar informações de logístis para ORDERING APPLICATION

### ISSUE THREAD

**Issue by eduardoalmeida** [Abrasel-Nacional/opendelivery#116]
Quando o PDV for responsável pelas duas integrações (Pedido e Logística) não existe uma maneira de informar o ORDERING APPLICATION dados da entrega.

Dados importantes para serem compartilhados:

- ETA
- status do entregador (PICKUP_ONGOING, DELIVERY_ONGOING, ORDER_DELIEVERED)
- externalTrackingURL
- geolocalization
- deliveryMan

**Comment by gui-camargo** [comment]
Olá @eduardoalmeida,

Conforme conversamos no comite, esta issue entrará no backlog do projeto, para evoluções futuras no padrão de logística.

**Comment by OpenDelivery-Tech** [comment]
Está sendo tratada na issue #134
