### ISSUE TITLE
[e-Deploy] Logistic - Get Delivery Details - Usando orderId como parâmetro

### ISSUE THREAD

**Issue by eduardoalmeida** [Abrasel-Nacional/opendelivery#117]
O problema de usar o orderId é que podemos ter a seguinte situação:
Um pedido de logistica é feito mas é rejeitado por não atender o tempo de entrega (por exemplo). Um segundo pedido é feito com um tempo maior e esse é aceito. 
Como as duas solicitações de logística são referentes ao mesmo pedido eles terão o mesmo orderId e não será possível saber qual retornar.
Sugestão mudar para o deliveryId que seria único por entrega.

**Comment by gui-camargo** [comment]
Olá @eduardoalmeida,

Conforme conversado no comite, foi incluído um texto explicando que deverá ser retornado apenas as informações do último evento ocorrido, seja ele um rejeição ou um aceite.

Já disponível na documentação BETA.

Changelog:

- **[GET /v1/logistics/delivery/{orderId}](https://abrasel-nacional.github.io/docs/versions/beta/#operation/logisticDetails) - Response Body**
  - added a explanation text about returning orders with more than 1 result (orders that were rejected on the first attempt).

  Text:
 
```
Since the same `orderId` may have more than one return (considering that it may have been rejected a few times before being accepted), then the response should return only the last attempt processed by the Logistics Service, be it an acceptance or a rejection.
```
