### ISSUE TITLE
[e-Deploy] Logistic - Get Delivery Details - Campos obrigatórios

### ISSUE THREAD

**Issue by eduardoalmeida** [Abrasel-Nacional/opendelivery#118]
Da mesma forma que o evento de tracking tinha campos obrigatórios que não fazem sentido para alguns estados (PENDING e REJECTED). O serviço de detalhes de pedido também:

- vehice
- deliveryPrice
- times

**Comment by gui-camargo** [comment]
Olá @eduardoalmeida,

Conforme conversado em comite, foi removida a obrigatoriedade dos campos.

Já disponível na versão BETA.

Changelog:

- **[GET /v1/logistics/delivery/{orderId}](https://abrasel-nacional.github.io/docs/versions/beta/#operation/logisticDetails) - Response Body**
  - Changed the requirement for the following properties:
    - vehicle
    - deliveryPrice
    - times
  
    These properties now are only **REQUIRED** when CURRENT `event>type` is different from `PENDING`, `REJECTED` and `CANCELLED`
