### ISSUE TITLE
[e-Deploy] - 422 no requestOrderCancellation

### ISSUE THREAD

**Issue by eduardoalmeida** [Abrasel-Nacional/opendelivery#12]
Foi definido que os métodos de atualização de pedido poderiam retornar 422 caso o Marketplace já tenha processa a solicitação. 
Para o método requestOrderCancellation, temos duas saídas possíveis: CANCELLED ou CANCELLATION_REQUEST_DENIED mas na resposta do 422 não dá para saber qual das duas ações foi tomada pelo MarketPlace.
Sugestão: no body da resposta 422 colocar um novo campo obrigatório: "cancellationStatus" com os valores CANCELLED ou CANCELLATION_REQUEST_DENIED

**Comment by gui-camargo** [comment]
Olá @eduardoalmeida,

Vamos levar essa questão para o comite do dia 22/09/2022, mas creio que não há problemas em adotar a sugestão.

**Comment by gui-camargo** [comment]
Olá @eduardoalmeida, 

Conforme a requisição, o campo foi adicionado ao body do response do HTTP 422.

![image](https://user-images.githubusercontent.com/80956588/199075218-2b8be56d-c60a-4d13-ab2d-241fda46e3ca.png)

Já está disponível na versão release candidate, e a issue ficará aberta até o merge com a versão release.

**Comment by gui-camargo** [comment]
Olá @eduardoalmeida 

A alteração já está disponível na versão release.

Changelog:
> [POST /v1/orders/{orderId}/requestCancellation](#operation/requestCancellation)
>- added propertie `cancellationStatus` to the 422 response body to indicate the result of the cancellation request in case of a duplicate event.


A issue será fechada.
