### ISSUE TITLE
[e-Deploy] - Obrigatoriedade do campo eta.updateMethod

### ISSUE THREAD

**Issue by eduardoalmeida** [Abrasel-Nacional/opendelivery#120]
Atualmente este campo não esta como "required" mas seu valor é uma enum e o valor nulo não faz sentido.
Sugestão seria alterar o campo para ser obrigatório.

**Comment by gui-camargo** [comment]
Olá @eduardoalmeida 

Conforme conversado no comite, o campo passará a ser obrigatório.

Já disponível na versão BETA.

Changelog:
- **[POST /v1/deliveryUpdate](https://abrasel-nacional.github.io/docs/versions/beta/#operation/newLogisticEvent) - Webhook Request Body**
  - changed propertie `eta.updateMethod` to required.

- **[POST /v1/logistics/availability](https://abrasel-nacional.github.io/docs/versions/beta/#tag/logisticPrice) - Response Body**
  - changed propertie `ETAs.updateMethod` to required.
