### ISSUE TITLE
Change term Delivery Man to Delivery Person

### ISSUE THREAD

**Issue by israelmelicio** [Abrasel-Nacional/opendelivery#121]
Delivery Person is a more correct form to refer to those who make a delivery.
We should change this term in all documentation and requests and responses.

**Comment by gui-camargo** [comment]
Olá @israelmelicio,

Conforme conversamos no comite, o termo foi ajustado em toda documentação.

Já disponível na versão BETA.

Changelog:
- changed the term **deliveryMan** to **deliveryPerson** across the whole document. Changed properties and enumerators are described in their respective endpoint below.

- **[GET /v1/logistics/delivery/{orderId}](https://abrasel-nacional.github.io/docs/versions/beta/#tag/logisticDetails/operation/logisticDetails) - Response Body**
- **[POST /v1/deliveryUpdate](https://abrasel-nacional.github.io/docs/versions/beta/#tag/logisticTracking/operation/newLogisticEvent) - Webhook Request Body**
  - renamed propertie `deliveryMan` to `deliveryPerson`
  
  - `rejectionInfo.reason`:  
    - renamed `NO_DELIVERYMAN_AVAILABLE` to `NO_DELIVERYPERSON_AVAILABLE`

  - `problem.reason`
    - renamed `DELIVERY_MAN_OCCURRENCE` to `DELIVERYPERSON_OCCURRENCE`
    - renamed `DELIVERY_MAN_WAITING_PAYMENT_FOR_ALREADY_PAID_ORDER` to `DELIVERYPERSON_WAITING_PAYMENT_FOR_ALREADY_PAID_ORDER`

- **[POST /v1/logistics/handleProblem/{orderId}](https://abrasel-nacional.github.io/docs/versions/beta/#tag/logisticOrder/operation/logisticsProblem) - Response Body**
  - `problem.reason`
    - renamed `DELIVERY_MAN_OCCURRENCE` to `DELIVERYPERSON_OCCURRENCE`
    - renamed `DELIVERY_MAN_WAITING_PAYMENT_FOR_ALREADY_PAID_ORDER` to `DELIVERYPERSON_WAITING_PAYMENT_FOR_ALREADY_PAID_ORDER`
