### ISSUE TITLE
[DeliveryVip] Pedidos Indoor

### ISSUE THREAD

**Issue by danieldocki** [Abrasel-Nacional/opendelivery#122]
Os objetos `customer`, `payments` de `order` estão como obrigatórios para pedidos indoor, mas no nosso caso quando um pedido indoor é realizado esses dados não são obrigatórios serem informados no momento do pedido, talvez colocar em discussão se esses objetos seriam obrigatórios quando ser do tipo `INDOOR`.

**Comment by gui-camargo** [comment]
Olá @danieldocki boa tarde.

Levamos essa questão para discutir no comite, mas ficamos com algumas duvidas e queriamos esclarecer melhor com você.

Você consegue participar do comite do dia 23/02/2023 as 9:00?

**Comment by OpenDelivery-Tech** [comment]
Olá @danieldocki 

Conforme conversado em comitê, as seguintes mudanças foram feitas na parte de indoor:

- Adicionada nova modalidade `TAB`
- Adicionado novo campo `tab` para indicação da comanda.

Objeto final:

![image](https://user-images.githubusercontent.com/129890133/229879168-161f6c1b-d881-4fb0-8df3-869354985c54.png)

As mudanças estarão disponíveis na versão 1.2.0 da documentação, mas ja podem ser acessadas na versão release candidate.
https://abrasel-nacional.github.io/docs/versions/rc/#tag/ordersDetails/operation/ordersDetails

**Comment by OpenDelivery-Tech** [comment]
As funcionalidades foram incluídas na v1.2.0.

Issue será fechada.
