### ISSUE TITLE
Entregador ao despachar pedido

### ISSUE THREAD

**Issue by borapedir** [Abrasel-Nacional/opendelivery#123]
No caminho /v1/orders/{orderId}/dispatch não tem a informação de quem efetuara a entrega, colocar em discursão se haveria possibilidade e enviar esta informação como opcional, em nossa plataforma o entregador é avaliado e pode receber gorjeta por pix.

**Comment by OpenDelivery-Tech** [comment]
Olá @borapedir,

Conforme conversado em comite, foram adicionadas informações sobre a entrega no body do endpoint POST /v1/orders/{orderId}/dispatch.

Objeto final:

![image](https://user-images.githubusercontent.com/129890133/231455110-1e46d5ac-d3c5-42f6-ae9c-2b7a5f7d15b4.png)

As mudanças estarão disponíveis na versão 1.2.0 da documentação, mas ja podem ser acessadas na versão release candidate:
https://abrasel-nacional.github.io/docs/versions/rc/#tag/ordersStatus/operation/dispatchOrder

**Comment by OpenDelivery-Tech** [comment]
As funcionalidades foram incluídas na versão v1.2.0.

Issue será fechada.
