### ISSUE TITLE
AvailabilityId do ItemOffer deveria ser opcional

### ISSUE THREAD

**Issue by EcleticaDev** [Abrasel-Nacional/opendelivery#124]
Durante a montagem do cardápio do pdv para ser enviado ao mkt, na parte de promoções e/ou disponibilidade de itens em determinados dias e horários, a documentação pede que sempre temos que enviar o availabilityId mesmo quando o item não possuir horario diferenciado ou preço promocional em determinado dia.

**Comment by OpenDelivery-Tech** [comment]
Olá @EcleticaDev 

Conforme conversado em comitê, as obrigatoriedades do campo `availabilityId` dos objetos de `Category` e `ItemOffer` serão removidas na próxima versão.

A descrição do campo também foi revisada.
Objeto final:

![image](https://user-images.githubusercontent.com/129890133/231456271-18555d09-689a-47da-b89c-8be17419b9ce.png)

As mudanças estarão disponíveis na versão 1.2.0 da documentação, mas ja podem ser acessadas na versão release candidate:
https://abrasel-nacional.github.io/docs/versions/rc/#tag/merchantStructure/Menu/ItemOffer

**Comment by OpenDelivery-Tech** [comment]
As funcionalidades foram incluídas na versão v1.2.0.

Issue será fechada.
