### ISSUE TITLE
[e-Deploy] - Evento CANCELLATION_DENIED

### ISSUE THREAD

**Issue by eduardoalmeida** [Abrasel-Nacional/opendelivery#125]
Na documentação da parte de cancelamento (https://abrasel-nacional.github.io/docs/#tag/ordersCancellation), quando o cancelamento é iniciado pelo Ordering Application é mencionado o evento CANCELLATION_DENIED (que deveria ser colocado no polling para confirmar o recebimento da API /denyCancellation.
O evento CANCELLATION_DENIED não está na lista de eventos possíveis do polling (https://abrasel-nacional.github.io/docs/#tag/ordersPolling/operation/pollingEvents) nem do webhook (https://abrasel-nacional.github.io/docs/#tag/ordersWebhook/operation/newEvent).

**Comment by OpenDelivery-Tech** [comment]
Olá @eduardoalmeida,

O evento `CANCELLATION_DENIED` foi incluído aos eventos do pedido:

Já está disponível na versão 1.1.1.

![image](https://user-images.githubusercontent.com/129890133/231456826-5351c0e9-46ce-434f-bff3-cb9037ae59e7.png)

A issue será fechada.
