### ISSUE TITLE
[e-Deploy] Logística: valor que o cliente pagou para entrega

### ISSUE THREAD

**Issue by eduardoalmeida** [Abrasel-Nacional/opendelivery#127]
Para Hubs logísticos um parâmetro para seleção de qual parceiro utilizar é quanto o cliente pagou de entrega. Dependendo do valor que o cliente pagou, pode-se escolher um parceiro logístico mais rápido mesmo sendo mais caro ou escolher um que demora mais mas cabe no valor da entrega.

Atualmente nos métodos de cotação e novo pedido temos o campo `totalOrderPrice`. A sugestão seria criar um `paidDeliveryFeePrice` com o valor que o cliente pagou de entrega

**Comment by OpenDelivery-Tech** [comment]
Olá @eduardoalmeida 

O campo orderDeliveryFee foi adicionado aos endpoints:
- POST /v1/logistics/delivery
- POST /v1/logistics/availability

Já disponível na versão v1.2.0

A issue será fechada.
