### ISSUE TITLE
[Epadoca] Pedido - Campo de email no Customer

### ISSUE THREAD

**Issue by flastowizka** [Abrasel-Nacional/opendelivery#128]
Existem alguns sistemas que resgatam os pedidos que precisam de algumas informações mais detalhadas, para geração de NF, notificação cliente, etc.
Por conta disso, sentimos a necessidade de dentro do customer do pedido incluir um novo campo chamado: email

Essa informação deve ser opcional, considerando que nem todos precisem enviar.

**Comment by OpenDelivery-Tech** [comment]
O campo `email` (opcional) foi incluido no objeto `customer` do body do pedido.

Já disponível na versão v1.2.0

A issue será fechada.
