### ISSUE TITLE
Alterações parciais nas informações da merchant

### ISSUE THREAD

**Issue by rafael-a-guimaraes** [Abrasel-Nacional/opendelivery#13]
Nos nossos testes o retorno do endpoint merchant ficou um pouco grande (para Starbucks em torno de 600 Kbytes) e tem uma carga grande de processamento para gerar e ler. Quando objetivo é fazer poucas alterações, poderia haver endpoints específicos o marketplace ler, por exemplo:
- Bloqueio de produtos que estão fora estoque
- Entrada de produtos em oferta
- Alteração pontual de horários de funcionamento

**Comment by CardosoGit** [comment]
Me parece que nesses casos a melhor solução é disponibilizar as pequenas alterações junto com a própria notificação do evento. Mas eu não vi um padrão para isso, ainda.

**Comment by gui-camargo** [comment]
Conforme discutido no comitê do dia 12/08/2021, o webhook de notificação de updates do merchant foi evoluído, com a possibilidade de se mandar uma lista de objetos de uma entidade que foi atualizada.

https://abrasel-nacional.github.io/docs/#operation/menuUpdated

Também foi incluído no backlog para as próximas versões a disponibilização de enpoints por parte da Ordering Application para que o Software Service faça updates diretos na plataforma de pedidos.
