### ISSUE TITLE
[e-Deploy] - Inconsistência no merchantUpdate

### ISSUE THREAD

**Issue by eduardoalmeida** [Abrasel-Nacional/opendelivery#130]
Em toda a documentação o método de merchant update é referenciado como merchantUpdated mas na URL da região ainda está como merchantUpdate

https://abrasel-nacional.github.io/docs/#tag/merchantUpdate/operation/menuUpdated

**Comment by OpenDelivery-Tech** [comment]
Olá @eduardoalmeida 

Vou revisar esses pontos e no comitê fazemos um repasse.

**Comment by OpenDelivery-Tech** [comment]
Toda a documentação foi revisada e a nomenclatura **merchantUpdate** foi adotada como padrão.
Apenas a URL se manteve como **menuUpdate** por questões de compatibilidade.

Já revisado na versão v1.2.0 da documentação.

A issue será fechada.
