### ISSUE TITLE
[PedePronto] Retorno das APIs que utilizam Autenticação

### ISSUE THREAD

**Issue by varronche** [Abrasel-Nacional/opendelivery#131]
Por favor, poderiam considerar a alteração de todos os retorno das APIs que utilizam a autenticação oauth2 de 403 para 401, pois muitos gateways de mercado impossibilitam a customização do retorno de erro, impossibilitando a implementação do Open Delivery conforme a especificação.

**Comment by OpenDelivery-Tech** [comment]
Olá @varronche 

Vamos levar a solicitação para o comitê, e provavelmente vamos adicionar o 401 como um retorno disponível, ao invés de alterar.

Por favor, peço que se possível participe do comitê do dia 04/05/2023 para contribuir com a discussão.

**Comment by OpenDelivery-Tech** [comment]
Foi incluído em todos os endpoints que utilizam autenticação, o código de retorno 401.

Já disponível na versão v1.2.0 da documentação.

A issue será fechada.
