### ISSUE TITLE
[PedePronto] Informação documentNumber do Customer no Order

### ISSUE THREAD

**Issue by varronche** [Abrasel-Nacional/opendelivery#132]
Devido a questões de segurança, poderiam considerar a retirada da informação do documentNumber do Customer dentro do payload do Order? Pois muitas certificações de leis de proteção de dados impedem que informações sensíveis, como o CPF do consumidor seja trafegado em payloads, como o de pedidos.

**Comment by OpenDelivery-Tech** [comment]
Olá @varronche 

Esse informação deixará de ser obrigatória a partir da versão 1.2.0 da documentação que será lançada em junho.

Caso queira, você pode acompanhar as alterações pela documentação do release candidate.
https://abrasel-nacional.github.io/docs/versions/rc/#tag/ordersDetails/operation/ordersDetails

**Comment by OpenDelivery-Tech** [comment]
Funcionalidade já disponível na versão v1.2.0 da documentação.

A issue será fechada.
