### ISSUE TITLE
[Ecletica]Método v1/merchant + merchant ID

### ISSUE THREAD

**Issue by EcleticaDev** [Abrasel-Nacional/opendelivery#133]
A issue propõe um entendimento/alteração a respeito do método v1/merchant que se encontra em:

https://abrasel-nacional.github.io/docs/#tag/merchantEndpoints/operation/getMerchant

Neste método, não há menção à variável {merchant_id} a qual entendemos ser uma chave essencial para listar o cardápio de um único estabelecimento dentro do padrão OpenDelivery.

Hoje, neste método que usa o verbo HTTP GET, a URL é somente v1/merchant

O que propomos é criar um parâmetro (variável) no final da própria URL : v1/merchant/{merchant_id}

Desta forma, configurando os servidores para trabalhar com URLs amigáveis/rotas conseguiremos capturar este novo parâmetro para ser usado na filtragem da API

**Comment by OpenDelivery-Tech** [comment]
Conforme conversado em comitê, não será criado nenhum endpoint novo em relação ao /merchant, mas foram incluídas instruções melhores em como utilizar o endpoint:

```
This section details the GET /v1/merchant endpoint.

This endpoint should be implemented by the Software Service and its URL should be informed to the Ordering Application.

The endpoint is designed so that each merchant has its own URL.

The specification recommends that the endpoint ends with the /merchant route, but this is not mandatory. The Software Service can implement the URL in any way it sees fit, as long as it contains information from only one merchant.
```

A issue será fechada.
