### ISSUE TITLE
[e-Deploy] - Webhook para atualização das informações de logística

### ISSUE THREAD

**Issue by eduardoalmeida** [Abrasel-Nacional/opendelivery#134]
Para casos onde o SOFTWARE SERVICE fica no meio do ORDERING APPLICATION e do LOGISTIC SERVICES.

Na versão 1.2, no método dispatch foi adicionado no body o objeto deliveryTrackingInfo. Isso permite que, quando o entregador pegue o pedido, o ORDERING APPLICATION seja atualizado com as informações de entrega. Porém, conforme o entregador vai se movimentando essa atualização não pode ser enviada para o ORDERING APPLICATION.

Sugestão: criar um outro webhook opcional /deliveryTracking que receba o mesmo objeto deliveryTrackingInfo e adicionar no objeto o geoLocalization
No objeto order, adicionar um boolean 'sendDeliveryTracking' com a mesma ideia do sendDelivered para controlar quando esse webhook opcional seria chamado.

**Comment by OpenDelivery-Tech** [comment]
Bom dia @eduardoalmeida 

Nós incluimos o endpoint `POST /v1/orders/{orderId}/tracking` no versão 1.2. Não seria o mesmo endpoint?

https://abrasel-nacional.github.io/docs/versions/rc/#tag/ordersTracking/operation/orderTracking

**Comment by OpenDelivery-Tech** [comment]
O endpoint `POST /v1/orders/{orderId}/tracking` e o campo `sendTracking` foram incluídos na versão 1.2.0 da documentação.

A issue será fechada.
