### ISSUE TITLE
[e-Deploy] - Clarificação sobre hospedagem de imagens

### ISSUE THREAD

**Issue by eduardoalmeida** [Abrasel-Nacional/opendelivery#135]
No nosso entendimento as informações que estão no json do /merchant deveriam ser usadas para sincronização dos dados entre as partes envolvidas.
Atualmente no json de cardápio da e-Deploy as URLs das imagens são válidas por 24 horas. A ideia da validade é não permitir que algum parceiro publique em sua aplicação uma URL do nosso sistema. 
O entendimento de um parceiro é que as imagens devem ser hospeadas pelo Software Service e devem estar sempre disponíveis para utilização no aplicativo deles.

Acredito que o modelo de sincronização faça mais sentido pois:
1 - não faz sentido o Software Service ter que ficar responsável pelos custos de hospedar imagens do Ordering Application.
2 - cria uma amarração desnecessária entre o Ordering Application e o Software Service que pode gerar problemas: campanha de uso do aplicativo impactada pois o servidor de imagens do Software Service não está devidamente escalado.

Uma possível solução para o problema seria a possibilidade das imagens poderem ser enviadas utilizando data:image/png;base64,DATA como acontece no iFood.

**Comment by OpenDelivery-Tech** [comment]
@eduardoalmeida 

Adicionei algumas instruções nos campos de imagem:

![image](https://github.com/Abrasel-Nacional/docs/assets/129890133/59559bbc-b904-44a2-8e04-023289d91bee)

e no Guideline:

![image](https://github.com/Abrasel-Nacional/docs/assets/129890133/351a0080-b056-4a3c-9611-e4acaabcbb9b)
