### ISSUE TITLE
[Pedido e Cardápio] Inclusão de Valor Promocional nos Itens

### ISSUE THREAD

**Issue by pqpgabes** [Abrasel-Nacional/opendelivery#136]
Temos um cliente que irá operar com valores promocionais nos produtos (de-por), mas o mesmo gostaria que ambos os valores (original e o promocional) pudessem ser vistos nos pedidos via padrão Open Delivery. A sugestão é incluir no bloco do Item um parâmetro para enviar o valor promocional - caso tenha. Abaixo um print do cenário:
![image](https://github.com/Abrasel-Nacional/docs/assets/101373420/62166422-c74c-4954-836b-16d3d42a75e4)

**Comment by OpenDelivery-Tech** [comment]
Olá @pqpgabes, bom dia.

Vamos levar essa issue para discussão no comitê do dia 27/07/2023.

Peço que se possível participe, para entendermos melhor as necessidades.

**Comment by OpenDelivery-Tech** [comment]
Olá @pqpgabes 

Conforme conversamos no comitê a documentação será alterada na próxima versão (v1.3.0) para refletir a informação.

A issue já está tratada na versão Release Candidate.
![image](https://github.com/Abrasel-Nacional/docs/assets/129890133/f6c2610f-2956-42b7-8237-b745c371af75)



https://abrasel-nacional.github.io/docs/versions/rc/#tag/ordersDetails/operation/ordersDetails

**Comment by OpenDelivery-Tech** [comment]
@pqpgabes, a mudança foi versionada junto com a v1.3.0.

Já disponível na versão release.

A issue será fechada.
