### ISSUE TITLE
[DeliveryVip] Dúvidas sobre o Order Tracking

### ISSUE THREAD

**Issue by danieldocki** [Abrasel-Nacional/opendelivery#137]
Na documentação nenhum objeto é requerido, fiquei com essa dúvida, nem mesmo o event, como pode ver:

![Screenshot 2023-07-21 at 11 14 02](https://github.com/Abrasel-Nacional/docs/assets/10542/fb09b661-c6e6-4e01-9480-6a37faed2162)

Outra dúvida é sobre o objeto "problem", ele pode vir junto com o objeto "event" ou somente ele?
Se vier somente ele vai ser um sobre um problema do último evento?

**Comment by OpenDelivery-Tech** [comment]
Olá @danieldocki 

Como não sabemos quais tipos de informação o PDV vai ter sobre a entrega, resolvemos deixar todos os campos não obrigatórios, porque ai o software pode mandar apenas os campos que ele possui. Não quisemos impor obrigatoriedades no momento.

Sobre o problem, ele é separado do event e a ideia é como você disse, ele indica um problema no evento atual.

**Comment by danieldocki** [comment]
PDV possivelmente pode não ter essa informações...

Mas se uma empresa de logistica poderia estar ouvindo os eventos dos pedidos e enviar essas informações?

**Comment by danieldocki** [comment]
Já esclarecido no comitê.
