### ISSUE TITLE
[Olga Tech] Cálculo do totalPrice do produto no order details 

### ISSUE THREAD

**Issue by tiolga** [Abrasel-Nacional/opendelivery#138]
Olá!
Encontramos uma situação de ambiguidade de interpretação em relação ao cálculo do valor de um produto:

Hoje ele é calculado desta forma (Segundo a [documentação](https://abrasel-nacional.github.io/docs/#tag/ordersDetails)):
```Total Price of the item. (quantity * unitPrice + optionsPrice)```

Nós acreditamos que o correto deveria ser:
```Total Price of the item. (quantity * (unitPrice + optionsPrice))```

Isto devido ao fato de produtos com quantidade maior que um e que contenham opcionais com valor não estão tendo o valor desses opcionais replicados. Dessa forma é cobrado o valor do produto N vezes (sendo N a quantidade de produtos) porém cada opcional somente uma vez. Assim o cliente vai ganhar o valor do opcional nos outros itens e pagar por eles somente uma vez. 

Faz sentido esse comportamento? Obrigado.

**Comment by OpenDelivery-Tech** [comment]
Olá @tiolga 

Creio que a sua interpretação está correta, vamos discutir esse ponto no comitê técnico, mas provavelmente teremos que fazer essa correção na documentação.

Obrigado pela issue.

**Comment by OpenDelivery-Tech** [comment]
Olá @tiolga 

O cálculo foi corrigido e já está disponível na versão release da documentação: v1.2.1

A Issue será fechada.
