### ISSUE TITLE
[Rappi] Modelo de conciliação

### ISSUE THREAD

**Issue by thiagohdeplima** [Abrasel-Nacional/opendelivery#139]
Acreditamos que o modelo de relatórios financeiros, atualmente em versão beta, deveriam ser alterados para que possam ser mais escaláveis e flexíveis para cenários que vão além de pedidos.

Abaixo, listamos alguns detalhes acerca disto.

**Composição de um pagamento**

Na Rappi - e acreditamos que em muitos players do mercado - um `paymentBatch` não é composto unicamente por `orders`.

Apesar de o pedido ser a principal fonte de geração de receita, podem haver uma série de descontos - muitos sequer relacionados a um pedido em específico - que impactam o valor final de um `paymentBatch`.

Na Rappi, um `PaymentBatch` é composto por N `transaction`, a qual pode ter ou não uma relação com uma `order`, como abaixo:

![image](https://github.com/Abrasel-Nacional/docs/assets/357059/04da9f99-c47a-4c9c-942c-282284ce1097)

**Escalabilidade do endpoint de obtenção de paymentBatch**

Listar todas as orders que têm relação direta com um pagamento em um único endpoint seguramente pode trazer problemas para `merchants` que possuem um volume maior de pedidos, ainda mais considerando que um único `paymentBatch` pode compensar pedidos de distintos `merchants` .

Idealmente, os pedidos ou qualquer outra entidade que componham um `paymentBatch` deveriam ser retornados em um endpoint distinto e com paginação.

**Comment by OpenDelivery-Tech** [comment]
Olá @thiagohdeplima, você poderia me passar alguma forma de contato? Gostaríamos de conversar melhor com você sobre esses pontos.

**Comment by thiagohdeplima** [comment]
Claro!

Podem me chamar no WhatsApp pelo número (11) 95609-4305. Por favor, comente aqui quando copiar este número, para que eu edite apagando o número para não deixá-lo público.

**Comment by OpenDelivery-Tech** [comment]
@thiagohdeplima , desculpe a demora. Pode a

**Comment by OpenDelivery-Tech** [comment]
Por falta de contato estamos fechando a Issue
