### ISSUE TITLE
[Pede Pronto] Dúvidas referentes a pedidos

### ISSUE THREAD

**Issue by anderson-otuka-dextra** [Abrasel-Nacional/opendelivery#14]
1. Pedidos do tipo TAKEOUT são pedidos para retirada em loja? ("para viagem", "para levar"?)

2. Como é definido o local/endereço de retirada de pedidos TAKEOUT?
O "order details" não tem essa informação - possui apenas endereço no caso de DELIVERY.
Pelo que entendemos, existe um evento específico para definir o local de retirada; ou seja, o pedido é feito, o lojista aceita, prepara, e define o local de retirada passando o endereço juntamente com o evento.

3. Qual a diferença, para pedidos TAKEOUT, dos modos: DEFAULT e PICKUP_AREA?
Um é para retirada em um único endereço? O outro é definido dinamicamente?

**Comment by gui-camargo** [comment]
Bom dia @anderson-otuka-dextra, seguem respostas:

> 1. Pedidos do tipo TAKEOUT são pedidos para retirada em loja? ("para viagem", "para levar"?)

Sim, exatamente.

> 2. Como é definido o local/endereço de retirada de pedidos TAKEOUT?

A ideia é que seja utilizado o próprio endereço do merchant, que vem informado no GET /merchant.
Não criamos um campo especifico, caso o endereço de retirada seja em um local diferente do endereço do estabelecimento. Se isto for necessário podemos discutir, para uma possível evolução.

> 3. Qual a diferença, para pedidos TAKEOUT, dos modos: DEFAULT e PICKUP_AREA?

O DEFAULT é para a retirada no balcão (ou area especifica) no endereço do estabelecimento.
O PICKUP_AREA é para ser utilizado para por exemplo, um restaurante que fica dentro de um shopping, o consumidor poderia parar numa vaga do estacionamento e indicar essa vaga (PICKUP_AREA) no aplicativo. Neste caso o restaurante recebe o evento PICKUP_AREA_ASSIGNED com o número da vaga, e algum funcionário vai levar o pedido até o carro.
Para ser utilizado este modo, a plataforma do marketplace precisa ter uma interface para que o usuário indique a PICKUP_AREA.

**Comment by anderson-otuka-dextra** [comment]
Mais uma pergunta.

4. Em que momento eu seto o pedido como CONCLUDED?
No fluxo, não está especificado o momento, se é:
a) quando o ec faz pooling do ultimo status (especificar quais são os ultimos status possiveis) ou
b) quando criamos o evento de ultimo status no pooling

**Comment by gui-camargo** [comment]
Oi @anderson-otuka-dextra,

Não existe um momento padrão para enviar este evento. Cada marketplace tem suas regras para concluir um pedido (por exemplo, quando o consumidor indica que recebeu, ou depois de um determinado tempo o pedido se conclui sozinho). O importante é vocês enviarem o evento ao restaurante, assim que no sistema de vocês o pedido for concluído.

Lembrando que o CONCLUDED do padrão é um EVENTO do pedido, e não um STATUS. Os STATUS do pedido, cada plataforma controla de sua maneira. Os EVENTOS são os gatilhos para que o restaurante mude o STATUS do seu lado.

Não há um padrão para os STATUS dos pedidos.

**Comment by varronche** [comment]
Bom dia @gui-camargo . Gostaria de entender melhor esse passo do CONCLUDED: hoje, na Pede Pronto, o EC nos informa quando o pedido esta concluido. Neste caso, como eu poderia fazer: criar um endpoint para ele chamar e nos informar que o pedido foi concluido?

**Comment by gui-camargo** [comment]
Olá @varronche,

Conforme discutido anteriormente, hoje o padrão não possui um endpoint específico para que o merchant informe a conclusão de um pedido ao Ordering Application. Neste caso teria que ser utilizada uma solução interna mesmo.

Mas estamos colocando no backlog do projeto esta rota, para evolução em versões futuras.
