### ISSUE TITLE
[Alterdata] Observação sobre obrigatoriedade do customer em pedidos delivery

### ISSUE THREAD

**Issue by renanscosta** [Abrasel-Nacional/opendelivery#140]
Após um comitê, o elemento customer passou a ser opcional, devido aos pedidos do tipo INDOOR. Entretanto, para pedidos DELIVERY, acredito não fazer muito sentido esse elemento ser opcional, sendo assim, sugiro uma breve observação no elemento, informando a obrigatoriedade em pedidos do tipo DELIVERY. 
Exemplo de observação: Required if the chosen type is DELIVERY.

**Comment by OpenDelivery-Tech** [comment]
Olá @renanscosta,

Conforme conversamos no comite a documentação será alterada na próxima versão (v1.3.0) para refletir a informação.

A issue já está tratada na versão Release Candidate.

![image](https://github.com/Abrasel-Nacional/docs/assets/129890133/9dc14bdc-53d7-4d78-8680-9372ed5b5294)

https://abrasel-nacional.github.io/docs/versions/rc/#tag/ordersDetails/operation/ordersDetails

**Comment by OpenDelivery-Tech** [comment]
@renanscosta , a mudança foi versionada junto com a v1.3.0.

Já disponível na versão release.

A issue será fechada.
