### ISSUE TITLE
[Mottu] [Número do Cliente] para tratativas 

### ISSUE THREAD

**Issue by CrisSjobom** [Abrasel-Nacional/opendelivery#141]
Notamos que não temos a informação do número do cliente que é muito importante para garantirmos o sucesso da entrega e evitarmos problemas como: O entregador dar o pedido como entregue sem de fato realizar a entrega ao cliente.
Utilizamos o número do cliente para alguns fluxos principais:
- Enviar o código de entrega para confirmar que a entrega foi realizada e reduzir extravios
- Realizar o mascaramento do telefone e permitir ligações entre entregador e cliente e entregador e loja quando acontecem casos de não conseguirem encontrar o cliente. 
Também usamos essa informação para disparar mensagens automáticas como: Informar o cliente que o entregador está no local da entrega
Podemos ter a inclusão dessa informação?

**Comment by OpenDelivery-Tech** [comment]
Olá @CrisSjobom, conforme conversamos, vamos levar esta questão para o comitê técnico do dia 10/08/2023.

Sua presença é fundamental para entendermos melhor os cenários.

**Comment by OpenDelivery-Tech** [comment]
@CrisSjobom o campo do numero do cliente foi incluído na versão v1.3.0

![image](https://github.com/Abrasel-Nacional/docs/assets/129890133/2e6b3aab-aea6-4038-9fe4-717aab7f9068)

Já disponível na versão release.

A issue será fechada.
