### ISSUE TITLE
[DeliveryVip] Brand no payments de orders

### ISSUE THREAD

**Issue by danieldocki** [Abrasel-Nacional/opendelivery#142]
O campo `brand` deve ser informado quando o for `PREPAID`, mas creio que ele deveria ser informado quando o `method` for do tipo `CREDIT`, `DEBIT`, `CREDIT_DEBIT`.

Porque o restaurante pode levar a maquininha para o pagamento quando ele for `PENDING` e faz o sentido informar a bandeira que o cliente pretende pagar.

**Comment by OpenDelivery-Tech** [comment]
Olá @danieldocki ,

Vamos levar para discutir no comitê, mas como essa é uma obrigatoriedade "de negocio", creio que se os membros concordarem, não teremos problemas em ajusta-la.

**Comment by OpenDelivery-Tech** [comment]
Olá @danieldocki 

Conforme conversamos no comitê a documentação será alterada na próxima versão (v1.3.0) para refletir a informação.

A issue já está tratada na versão Release Candidate.
![image](https://github.com/Abrasel-Nacional/docs/assets/129890133/12f01502-74c7-4dca-aa74-ba652d8f1dc1)


https://abrasel-nacional.github.io/docs/versions/rc/#tag/ordersDetails/operation/ordersDetails

**Comment by OpenDelivery-Tech** [comment]
@danieldocki, a mudança foi versionada junto com a v1.3.0.

Já disponível na versão release.

A issue será fechada.
