### ISSUE TITLE
[Olga Tech] Order Details: Inclusão do cupom de desconto no nó discounts

### ISSUE THREAD

**Issue by tiolga** [Abrasel-Nacional/opendelivery#143]
Olá,tudo certo?
O restaurante deseja saber qual foi o cupom de desconto que gerou o desconto em si. 
Hoje é enviado somente o tipo e valor do desconto no order details. 
Seria interessante um novo campo opcional chamado "CODE" (ou similar) para esse caso.
Assim os restaurantes conseguirão "trackear" as suas campanhas envolvendo cupons de desconto.

**Comment by OpenDelivery-Tech** [comment]
Olá @tiolga 

Conforme conversamos no comitê a documentação será alterada na próxima versão (v1.3.0) para refletir a informação.

A issue já está tratada na versão Release Candidate.
![image](https://github.com/Abrasel-Nacional/docs/assets/129890133/c91d4864-6abf-437d-9542-f545af85b25e)

https://abrasel-nacional.github.io/docs/versions/rc/#tag/ordersDetails/operation/ordersDetails

**Comment by OpenDelivery-Tech** [comment]
@tiolga, a mudança foi versionada junto com a v1.3.0.

Já disponível na versão release.

A issue será fechada.
