### ISSUE TITLE
[ Mottu ][ Dados Geolocacionais ] Redução de casas decimais em dados geolocacionais no envio de atualização de eventos de entrega

### ISSUE THREAD

**Issue by yan-almeida** [Abrasel-Nacional/opendelivery#144]
Como exemplo, temos um geoloc. `{"latitude":-23.5867444,"longitude":-46.6456}` - o que geraria um erro durante a validação na atualização de eventos de uma entrega.

A ideia seria diminuir a quantidade de casas decimais obrigatórias - atualmente, são **05 (cinco)**.

**Comment by OpenDelivery-Tech** [comment]
Olá @danieldocki 

Conforme conversamos no comitê a documentação será alterada na próxima versão (v1.3.0) para refletir a informação.

A issue já está tratada na versão Release Candidate.
![image](https://github.com/Abrasel-Nacional/docs/assets/129890133/88e44c80-46f7-4674-9e38-3b8e20392d0f)

https://abrasel-nacional.github.io/docs/versions/rc/

**Comment by OpenDelivery-Tech** [comment]
@yan-almeida, a mudança foi versionada junto com a v1.3.0.

Já disponível na versão release.

A issue será fechada.
