### ISSUE TITLE
[UaiRango] Adicionar o campo "name" em ItemOffer e Options

### ISSUE THREAD

**Issue by IagoArauj** [Abrasel-Nacional/opendelivery#146]
Em nosso cardápio, as duas entidades possuem este campo para diferenciação dentro do app de delivery, e hoje este campo não existe no padrão.
Seria interessante esta adição.

**Comment by OpenDelivery-Tech** [comment]
Olá @IagoArauj,

Como o itemOffer e o option sempre está vinculado a um item, a ideia é que eles assumam o nome do item.
Mas podemos levar essa issue para o comitê do dia 05/10, para entendermos o seu caso e discutir com os outros membros.

Peço que por favor participe.

**Comment by OpenDelivery-Tech** [comment]
Olá @IagoArauj, conforme já esclarecido em comite, os campos devem assumir o `name` do `item` relacionado.

![image](https://github.com/Abrasel-Nacional/docs/assets/129890133/1f49c51b-883c-4c97-b04f-165e191d0384)
https://abrasel-nacional.github.io/docs/#tag/merchantStructure/Menu/Item

![image](https://github.com/Abrasel-Nacional/docs/assets/129890133/cf600dfb-ae02-495c-8b25-933357256dbe)
https://abrasel-nacional.github.io/docs/#tag/merchantStructure/Menu/ItemOffer

A issue será fechada. Caso haja alguma outra dúvida relacionada, favor reabrir a issue.
