### ISSUE TITLE
[Ayo Entregas] Possibilidade de utilizar um "internalId" no corpo das entregas

### ISSUE THREAD

**Issue by ArNeto19** [Abrasel-Nacional/opendelivery#147]
Referente à criação de nova `delivery`.

Para integrações de sistemas que já utilizem padrões diferentes de criação de IDs, diferentes do proposto UUID, seria interessante um campo para armazenar esse id próprio, como um `internalId`.

**Comment by OpenDelivery-Tech** [comment]
Olá @ArNeto19 

Conforme conversamos em comitê, ficou definido que não era necessário a criação deste campo.

A issue será fechada. Qualquer outra dúvida relacionada, favor reabrir a issue.
