### ISSUE TITLE
[Pede Pronto] Dúvida sobre o domínio das informações sobre as credenciais de Webhook

### ISSUE THREAD

**Issue by erichideki** [Abrasel-Nacional/opendelivery#148]
Olá pessoal, tudo bem?

Por gentileza, estamos com uma dúvida relacionada ao domínio da informação relacionada a pedidos webhook.

https://abrasel-nacional.github.io/docs/#tag/ordersWebhook

X-App-Id | An Unique Identificator of the Ordering Application
X-App-MerchantId | An Unique Identificator of the Merchant receiving the order
X-App-Signature | SHA256 hash of the request body, using the client secret as the key

Nos casos de X-App-MerchantId e X-App-Signature, quem envia estes dados é o Ordering application ou o Software Service?

Obrigado!

**Comment by OpenDelivery-Tech** [comment]
Olá @erichideki,

Vamos lá

X-App-Id - Esse Id identifica a Pede Pronto para quem está recebendo o post webhook, então é um Id de vocês . O ideal é que vocês usem o mesmo App-Id para todos as integrações, independente do parceiro.

X-App-MerchantId: Esse é o id do merchant cadastrado no sistema de Vocês . Esse Id pode ter sido passado pelo parceiro ou vocês podem ter criado ele, mas o importante é que é o Id que identifica a loja/vendor/merchant/restaurante.

X-App-Signature: Como diz na descrição, essa é uma assinatura que valida que esse requisição é verdadeira. As instruções para cria-las estão aqui:
![image](https://github.com/Abrasel-Nacional/docs/assets/129890133/5b5f0d5c-dff2-4672-acc3-5b7792f155f0)
https://abrasel-nacional.github.io/docs/#tag/ordersWebhook

Vocês devem informar esses 3 campos no header de todas as chamadas via webhook.

Se tiver mais duvidas estou a disposição.

**Comment by erichideki** [comment]
Obrigado. Fica mais claro assim o domínio destas informações e quem deve enviá-las.
