### ISSUE TITLE
[e-Deploy] - Ready for Pickup na Logística

### ISSUE THREAD

**Issue by eduardoalmeida** [Abrasel-Nacional/opendelivery#149]
Estamos fazendo integração com a Husky e eles possuem uma regra de acelerar / alocar entregadores quando o pedido já está pronto mas, atualmente, no padrão logística não há como informar o parceiro de logística de que o pedido está pronto.

A sugestão seria criar um webhook opcional parecido com o do order:

POST /v1/logistics/readyForPickup/{orderId}
 
 sem body e com a mesma autorização (OAuth)
 
 Para manter o padrão, teria também que alterar o "Request new delivery" para ter um campo boolean: notifyReadyForPickup. Para manter a compatibilidade este campo deve ser opcional e, na sua ausência, deve-se condiderá-lo como false.

**Comment by OpenDelivery-Tech** [comment]
Olá @eduardoalmeida,

Vamos discutir essa issue no comitê técnico desta semana.
Esperamos contar com sua presença.

**Comment by OpenDelivery-Tech** [comment]
Olá @eduardoalmeida,

Conforme discutido em comitê, a funcionalidade será incluída na versão 1.4.0 da documentação.

Mudanças:
- Adicionado novo endpoint POST /v1/logistics/readyForPickup/{orderId}
- Adicionado novo campo notifyReadyForPickup no endpoint POST /v1/logistics/delivery

A issue será fechada assim que a versão entrar em produção.

**Comment by OpenDelivery-Tech** [comment]
Olá @eduardoalmeida 

A funcionalidade já está disponível na versão v1.4.0 da API

Changelog:

```
POST /v1/logistics/readyForPickup/{orderId}

  - Added this new optional endpoint for the MERCHANT to notify the Logistic Service that an order is ready for pickup. 
  
  - Changed the delivery order flow diagram to reflect the new endpoint.

POST v1/logistics/delivery

  - Added a new optional propertie `notifyReadyForPickup` to indicate if the **Logistics Service** must be ready to receive a Ready for Pickup request. 
```

A issue será fechada.
