### ISSUE TITLE
Melhorias para serviços de Pickup e Delivery na mesma loja

### ISSUE THREAD

**Issue by rafael-a-guimaraes** [Abrasel-Nacional/opendelivery#15]
Avaliar as seguintes mudanças na estrutura:
- Como o availability não está associada a um service, são necessários 2 menus para Delivery e Pickup pois alguns itens do Pickup não estão disponíveis para Delivery. Se o availability suportasse um array de services esta informação poderia ser passada em um único menu
- O campo minOrderValue poderia associado ao service porque no Pickup pode ser diferente do Delivery

**Comment by gui-camargo** [comment]
Conforme discutido no comitê técnico do dia 05/08/2021, na primeira versão da API do Open Delivery será mantido o Pickup e o Delivery através da entidade 'Service', mas foi registrado no Backlog do projeto para ser discutido nas evoluções das próximas versões da API.
