### ISSUE TITLE
[e-Deploy] - Obrigatoriedade do "POST /events/acknowledgment" em integrações com webhook

### ISSUE THREAD

**Issue by eduardoalmeida** [Abrasel-Nacional/opendelivery#150]
Atualmente a documentação não está muito clara sobre à necessidade do "POST /events/acknowledgment" quando a integração acontece com webhook

Na documentação este método está agrupado dentro do "Polling" dando a entender que, para webhooks não seria necessário.

Porém esta parte:
Acknowledgment Events
When receiving new events, the Software Service should always send acknowledgement so that the Ordering Application does not send that same event again;

dá a entender que é obrigatório o envio do ACK mesmo para eventos recebidos por webhook.

A parte específica de webhook parece deixar claro que o 200 já seria o ACK do evento.

Também temos esta parte
Order Event Reception
Through Order Events, the 'Ordering Application' communicates to the 'Software Service' the existence of a new order, as well as the other events of the order lifecycle.

Open Delivery provides two ways for merchant Software Service to be aware of new events:

Polling: Receiving events through polling provided by the 'Ordering Application' is the standard way Open Delivery works, and its implementation is mandatory.

Webhook: Optionally it is recommended the implementation of a webhook by the merchant Software Service for the Ordering Applications to send new events directly, ensuring a much faster communication.

que diz que o Polling é obrigatório então o ordering application teria que implementar o /events/acjnoledgement

Acredito que seria interessante deixar bem claro essa obrigatoriedade ou não.

**Comment by OpenDelivery-Tech** [comment]
Boa Tarde @eduardoalmeida 

Vamos falar amanhã no comitê sobre esse tema. Contamos com sua presença.

**Comment by OpenDelivery-Tech** [comment]
@eduardoalmeida 

Conforme conversamos no comite os textos foram alterados para deixar mais claro que o webhook não necessita do ack.

Estará disponível na versão 1.4.0.

A issue será fechada após o merge da versão.

**Comment by OpenDelivery-Tech** [comment]
Olá @eduardoalmeida 

Os textos já foram corrigidos e estão disponíveis na versão v1.4.0 da API:

Changelog:

```
  - Changed the text in the section on receiving events to indicate that ACKNOLODGMENT is only required for those working via POLLING.
    The text has also been changed to indicate that the Ordering Application can work with either of the two services and that POLLING is not required as a mandatory implementation. (Contrary to what was previously understood.)
```

A issue será fechada.
