### ISSUE TITLE
[Hub Delivery] - Virtual brands (Marcas Virtuais)

### ISSUE THREAD

**Issue by hubdelivery** [Abrasel-Nacional/opendelivery#152]
Gostaria de avaliar a possibilidade de expansão do modelo de catálogo e pedidos para virtual brands (marcas virtuais).

Hoje temos clientes que operam dentro do mesmo CNPJ diversas marcas e o padrão atual não comporta o modelo de marcas virtuais para catálogo e pedidos.

**Comment by OpenDelivery-Tech** [comment]
Olá @hubdelivery 

Conforme discutido em comitê, a funcionalidade será incluída na versão **1.4.0** da documentação.

Mudanças:

Adicionado nova propriedade `virtualBrands` nos endpoints: 
- GET /v1/events:polling
- POST /v1/newEvent (webhook)
- POST /v1/orders/{orderId}

A issue será fechada assim que a versão entrar em produção.

**Comment by OpenDelivery-Tech** [comment]
Olá @hubdelivery 

O novo campo já está disponível na versão v1.4.0 da API.

Changelog:
```
- GET v1/events:polling 
- POST /orderUpdate (WEBHOOK)
- GET /v1/orders/{orderId}

  - Added a new optional propertie `virtualBrand`.  
    This should be used as an alternative id for the merchant, in cases where the same merchant has different identifications or brands (such as dark kitchens).
```

A issue será fechada.
