### ISSUE TITLE
[Mottu][eDeploy] Solicitação de Implementação de Propriedades Opcionais para Identificação de Pedidos de Fontes Terceiras

### ISSUE THREAD

**Issue by yan-almeida** [Abrasel-Nacional/opendelivery#153]
Gostaria de abordar uma questão que tem sido recorrente em nossos processos de criação de pedido.

Atualmente, ao criarmos um pedido seguindo o padrão estabelecido na documentação fornecida ([link para documentação](https://abrasel-nacional.github.io/docs/#tag/logisticOrder)), realizamos uma verificação de duplicidade cruzando informações como `orderId`, `orderDisplayId` e `merchant.id`. No entanto, temos observado casos em que pedidos provenientes de outras fontes não nos fornecem os dados originais essenciais para essa validação.

Propomos a inclusão de propriedades opcionais em nossas requisições, tais como `sourceOrderId`, `sourceOrderDisplayId` e `sourceName` (seria extremamente necessário que soubessemos a fonte que originou o pedido para que pudessemos realizar a confirmação de entrega conforme a origem), que nos permitiriam identificar adequadamente pedidos provenientes de fontes terceiras. Com essa informação adicional, seríamos capazes de evitar a duplicidade de pedidos que, embora idênticos, são originados de fontes distintas, apresentando `orderId` e `orderDisplayId` diferentes.

Essa medida não apenas melhoraria nossa capacidade de gerenciar pedidos, mas também contribuiria para a eficiência operacional, garantindo uma entrega mais precisa e satisfatória para nossos clientes.

Agradecemos a atenção dedicada a esta questão e esperamos uma análise cuidadosa para a implementação dessas propriedades opcionais.

Atenciosamente,

Mottu

**Comment by OpenDelivery-Tech** [comment]
Olá @yan-almeida 

Conforme conversado no comitê, foi explicado que os campos `SourceAppId` e  `SourceOrderId` já existem no padrão e podem ser utilizados para tratar a situação de vocês.

Nenhuma mudança será feita e a issue será fechada.
