### ISSUE TITLE
[Mottu][e-deploy] adição de formatos de número de telefone no campo "customerPhone"

### ISSUE THREAD

**Issue by yan-almeida** [Abrasel-Nacional/opendelivery#154]
Hoje, do lado da mottu, temos trabalhado com números de telefones nos seguintes formatos: `+5561911112222`, `61911112222` e `0800900000,00000000` (para URAs reversas). Gostaríamos de sugerir estes formatos - ou similares.

Atenciosamente,

Mottu

**Comment by OpenDelivery-Tech** [comment]
Olá @yan-almeida 

Conforme discutido em comitê, a funcionalidade será adaptada na versão **1.4.0** da documentação.

Mudanças:

- Adicionado novo campo `customerPhoneLocalizer` no endpoint POST /v1/logistics/delivery

A issue será fechada assim que a versão entrar em produção.

**Comment by OpenDelivery-Tech** [comment]
@yan-almeida 

A alteração já está disponível na versão v1.4.0 da API.

Changelog:

```
POST v1/logistics/delivery

  - Added a new optional propertie `customerPhoneLocalizer` to indicate the order or customer localizer information to a call center.
```

A issue será fechada.
