### ISSUE TITLE
Tratamento do Customer documnetNumber

### ISSUE THREAD

**Issue by jamessgoulart** [Abrasel-Nacional/opendelivery#155]
Para mim, nao esta claro como deve ser tratado o Customer documentNumber caso o cliente nao preencha o campo de CPF. Devo enviar uma string vazia, nula, zerada...?

**Comment by danielgoncalves** [comment]
O atributo `documentNumber` não é requerido. Basta não informá-lo no objeto `customer`.

**Comment by OpenDelivery-Tech** [comment]
Bom dia @JamesGoulartdotcom 

Como disse o @danielgoncalves, basta omitir o campo no objeto.

No nossos Guidelines, informamos o tratamento de campos nulos:

![image](https://github.com/Abrasel-Nacional/docs/assets/129890133/dcb9b045-fdcf-4a54-8cb2-ee8eb6457c31)

Qualquer outra duvida estamos a disposição.

**Comment by jamessgoulart** [comment]
Perfeito. Obrigado pelo esclarecimento!
