### ISSUE TITLE
Misspelled `standard` as `stantard` in openapi.yaml

### ISSUE THREAD

**Issue by LuizDudu** [Abrasel-Nacional/opendelivery#156]
On line 220 in the openapi.yaml there is a misspelled word `stantard`

`Once the endpoints are implemented, the parties interested in integrating via the Open Delivery stantard should provide some parameters for the other party to correctly connect to its routes.`

**Comment by OpenDelivery-Tech** [comment]
Hi @LuizDudu 

Thanks for the issue.
The text has been corrected and it made in time for the v1.4.0 that is out today.

The issue will be closed.
If you have any other comments, you can reopen it.
