### ISSUE TITLE
Duvida: Como lidar com produtos com estrutura de PIZZA ?

### ISSUE THREAD

**Issue by LuizDudu** [Abrasel-Nacional/opendelivery#158]
Estou implementando `/v1/merchant` endpoint e estou com problemas em como definir a Pizza vinda do Ifood para Open Delivery a pizza do Ifood tem um campo que informa que aquele produto é uma pizza e deve ser tratado como tal. Os dados do item pizza do ifood tem CRUST, EDGE, SIZE, TOPPINGS.

Eu posso converter corretamente os items tipo PIZZA mas quem pedir os dados não vai ter indicação que aquele Item deve ter uma certa estrutura.

Eu olhei na documentação e não achei como eu poderia dizer que um item é uma Pizza no Open Delivery(v1.4)
Se não existe, alguém poderia me dar uma direção nessa situação de ter os dados prontos para quem pedir o Merchant

**Comment by OpenDelivery-Tech** [comment]
Olá @LuizDudu,

O jeito de tratar Pizzas, no padrão do Open Delivery seria utilizando a parte de Grupos de Opções (optionGroups).

Temos um exemplo prático disso na nossa ferramenta de geração de menus.

[https://abrasel-nacional.github.io/opendelivery-menu-generator/](https://abrasel-nacional.github.io/opendelivery-menu-generator/)

Escolha o exemplo da Pizza, e será retornado o JSON para você.

Você também pode gerar o menu para ter uma visualização completa dos campos e suas interações:
![image](https://github.com/user-attachments/assets/ddf09304-adc7-4c57-8704-352cee68021a)

Se tiver mais duvidas, por favor nos avise.
