### ISSUE TITLE
Esclarecimentos na documentação

### ISSUE THREAD

**Issue by rafael-a-guimaraes** [Abrasel-Nacional/opendelivery#16]
- O formato de data será sempre MM/DD/YYYY? Há locais da documentação onde o dia está com 1 dígito, por exemplo "5/06/2021", este formato deve ser suportado?
- O formato YYYY-MM-DD que é mais comum também deve ser suportado?
- Quando o objetivo é informar que o merchant está fechado no feriado, devemos retornar timePeriod : {} ?

**Comment by danielgoncalves** [comment]
É, tem umas discrepâncias. 
Pela documentação [1] eu fiquei com a impressão de datas e horas serem todas no padrão ISO 8601, embora a documentação não seja explícita.

[1] https://abrasel-nacional.github.io/docs/#section/General-guidelines

**Comment by gui-camargo** [comment]
Oi pessoal, 
Como o Daniel falou a ideia é seguir o ISO8601. Vou dar uma revisada nos campos de data, e corrigir caso necessário.

**Comment by gui-camargo** [comment]
Pessoal, apenas corrigindo meu comentário anterior, nós estamos seguindo os formatos providos pelo Open API (que seguem o ISO8601)

![image](https://user-images.githubusercontent.com/80956588/128235235-f893f0ae-4ec5-4f42-a3df-c6b5c9f058bb.png)

O Open API não possui uma definição apenas para o 'time' então a ideia é seguir a ISO.

Vocês podem me apontar alguns exemplos de campos que estão com inconsistência por favor?

**Comment by danielgoncalves** [comment]
Eu comentei que haviam discrepâncias, mas eu revisei manualmente a documentação inclusive experimentando algumas buscas e não encontrei nada fora do padrão. Não há discrepâncias nessa documentação, talvez em outras que eu tenha visto, e foram muitas 😅

**Comment by gui-camargo** [comment]
Conforme discutido no comitê técnico do dia 05/08/2021, o formato de data continua seguindo o padrão do Open API. Foi adicionada na documentação, na parte de General Guidelines, exemplos melhores de como utilizar cada um dos formatos de data. 

http://localhost:9093/-307623811#section/General-guidelines
