### ISSUE TITLE
Adicionar preparationTime na estrutura Delivery na API Order

### ISSUE THREAD

**Issue by TotvsKnD** [Abrasel-Nacional/opendelivery#166]
Boa tarde, solicito a adição da propriedade **preparationTime** na estrutura Delivery da API Order, esta propriedade é necessária para atender o mapeamento ao modelo iFood como segue :

![image](https://github.com/user-attachments/assets/5749fc19-d083-4641-b072-b6180c9ce4c7)

Referencia iFood ; https://developer.ifood.com.br/pt-BR/docs/guides/shipping/#detalhes-do-pedido

Grato
Kennedy E Silva ( TOTVS )

**Comment by gui-camargo** [comment]
Olá @TotvsKnD 

Vamos levar a issue para discussão no comitê técnico que acontecerá nesta quinta  (07/11/2024) as 11:00.
Por favor se programe para participar.

**Comment by TotvsKnD** [comment]
Solicitação discutida e não aderente a API Order, sendo assim estou encerrando

Grato
Kennedy E Silva - TOTVS
