### ISSUE TITLE
WebHook - Atualização do status Confirmed

### ISSUE THREAD

**Issue by JanaMarinS** [Abrasel-Nacional/opendelivery#17]
Na documentação na seção do [Webhook](https://abrasel-nacional.github.io/docs/#operation/newEvent), ao selecionarmos o eventType de **Confirmed** em `Exemple`, é necessario enviar a prop de **metadata**, nele há o **expectedPreparationStartTime**.
O **expectedPreparationStartTime** seria a data/hora em que o preparo do pedido foi iniciado ou seria a data/hora em que ele possivelmente ficaria pronto ou seria algo de agendamento do pedido? 

![Captura de tela de 2021-08-24 13-17-20](https://user-images.githubusercontent.com/43681114/130654069-f50fb7a3-79f5-42e5-8658-bf3db08e95f1.png)

**Comment by gui-camargo** [comment]
Olá @JanaMarinS.

A ideia é que, considerando os marketplaces que tem a logística própria, o campo possa ser utilizado para indicar ao restaurante um melhor horário de início de preparação do prato, considerando o tempo para o entregador chegar ao estabelecimento, assim otimizando o preparo para ser concluído perto da chegada do entregador.

Isso esclarece sua dúvida?

Vou melhorar a descrição do campo, para deixar mais claro.

**Comment by eduardoalmeida** [comment]
Olá @gui-camargo,
não seria melhor o campo ser um "expectedDeliveryManArrival" ou algo do tipo. Dependendo do pedido o tempo de preparo pode variar e quem tem essa lógica é o restaurante. Então acredito que seja melhor o marketplace informar qual o horário estimado de chegada do entregador e o software de PDV usa essa informação da maneira que lhe for mais conveniente.

**Comment by gui-camargo** [comment]
Oi @eduardoalmeida,

Podemos levar esse assunto para discussão no comitê, mas não queríamos misturar campos de logística, com os campos do pedido, pois já vamos ter a parte das apis de logística. Então pensei em deixar uma descrição mais genérica:

"Expected preparation start time after Order Confirmation. This can be used by the Ordering Application to inform the merchant to delay the start of the preparation for any reason."

O que vocês acham?
De qualquer maneira vou colocar este assunto em pauta.

**Comment by gui-camargo** [comment]
Conforme conversado no comitê do dia 02/09/2021, como o campo está sendo praticamente sendo utilizado para questões de logística, foi decidido pela retirada deste campo. 

A issue ficará aberta até o próximo comitê do dia 09/09/2021, para novos comentários e discussões referente a retirada ou não do campo.

**Comment by gui-camargo** [comment]
A remoção do campo foi contemplada na versão rc3. Issue será fechada.
