### ISSUE TITLE
Autenticação endpoint /merchant

### ISSUE THREAD

**Issue by gui-camargo** [Abrasel-Nacional/opendelivery#18]
No comitê do dia 19/08/2021 foi tratado o assunto da autenticação do endpoint **/merchant.** 
https://abrasel-nacional.github.io/docs/#operation/getMerchant

Na versão de lançamento dos testes (rc0), a documentação estava considerando o oauth2 para a autenticação deste endpoint. Mas considerando que este é o único endpoint (com exceção do webhook de pedidos) onde o 'host' é o Software Service e não a Ordering Application. Na discussão vimos que seria um ponto de complicação colocar todo o tratamento do oauth2, com a requisição de tokens para acessar apenas 1 endpoint, que não contem informações tão sensíveis. 

Com isso foi sugerido continuar utilizando o oauth2 com clientId e clientSecret mas já voltando a informação diretamente, sem necessitar acessar um endpoint /token anteriormente. Mas estudando os flows do oauth2 verifiquei que sempre é necessário passar por um endpoint de token (onde é informado o clientId e o clientSecret).

A ideia para o Open Delivery é utilizar um id e uma secret, mas que elas sejam enviadas diretamente via Header da chamada, sem ser necessário passar um token. Com isso proponho utilizar o conceito de **apiKey**, disponibilizado pelo Open API:

https://swagger.io/docs/specification/authentication/api-keys/

Assim propondo duas keys: id e key

![image](https://user-images.githubusercontent.com/80956588/130973462-2af88b4c-34eb-4521-86f8-79de76afa847.png)

O unico ponto das API Key é que não temos como utilizar os scopes, mas como é para 1 endpoint só, não vejo problemas.

Obs: Os demais endpoint continuam com a autenticação via oauth2.

Gostaria de ouvir a opnião de vocês e podemos levar para discussão no comitê do dia 02/09/2021

Abraço
Guilherme

**Comment by rafael-a-guimaraes** [comment]
Guilherme, para nós, receber apiKey e appId como parâmetros no header da requisição não é um problema. De fato, eles são equivalentes ao clientId e clientSecret do Oauth. Se quiser simplificar mais, é possível também receber somente o apiKey, neste caso eu geraria um apiKey com um string base64 contendo as informações de clientId e clientSecret que necessitamos para autenticar a chamada.

**Comment by gui-camargo** [comment]
A autenticação foi alterada para a apiKey conforme discutido em comitê e está disponível na versão rc3.

https://abrasel-nacional.github.io/docs/#tag/authentication

Issue será fechada.
