### ISSUE TITLE
Status Code para Acknowledge

### ISSUE THREAD

**Issue by samuel-silva-dc** [Abrasel-Nacional/opendelivery#19]
Ao receber o request body do endpoint /events/acknowledgment e, por ventura, haver alguma erro em algum dos campos, como: uuid invalido ou campo vazio. Retornamos o status code 400(bad request)?

OBS: Na documentação está mapeado os status code somente 403 e 503.

Exemplo de request body em /events/acknowledgment
`
[
    {
        "@id": "",
        "orderId": "",
        "eventType": ""
    }
]
`

Segue o link da documentação: https://abrasel-nacional.github.io/docs/#tag/ordersPolling/paths/~1events~1acknowledgment/post

**Comment by gui-camargo** [comment]
Olá @samuel-silva-dc, irei revisar as respostas de todos os endpoints, e acrescentar a resposta nos endpoints necessários.

**Comment by gui-camargo** [comment]
Acrescentado e corrigido os status codes na versão rc3 dos seguintes endpoints:

/merchantStatus

400 - Bad Request - Adicionado
/merchantUpdate (webhook)

400 - Bad Request - Adicionado
/events:polling

400 - Bad Request - Adicionado
/events/acknowledgment:

400 - Bad Request - Adicionado
404 - Not Found - Adicionado
/newEvent (webhook)

400 - Bad Request - Adicionado
/orders/{orderId}:

400 - Bad Request - Corrigido
403 - Forbidden - Adicionado
404 - Not Found - Corrigido
503 - Service Unavailable - Corrigido
/orders/{orderId}/confirm:

400 - Bad Request - Adicionado
404 - Not Found - Adicionado
/orders/{orderId}/readyForPickup:

400 - Bad Request - Adicionado
404 - Not Found - Adicionado
/orders/{orderId}/dispatch:

400 - Bad Request - Adicionado
404 - Not Found - Adicionado
/orders/{orderId}/requestCancellation:

400 - Bad Request - Adicionado
403 - Forbidden - Adicionado
404 - Not Found - Adicionado
503 - Service Unavailable - Corrigido
/orders/{orderId}/acceptCancellation:

400 - Bad Request - Adicionado
403 - Forbidden - Adicionado
404 - Not Found - Adicionado
503 - Service Unavailable - Corrigido
/orders/{orderId}/denyCancellation:

400 - Bad Request - Adicionado
403 - Forbidden - Adicionado
404 - Not Found - Adicionado
503 - Service Unavailable - Corrigido
/salesReport:

400 - Bad Request - Adicionado
/merchantList:

400 - Bad Request - Corrigido
404 - Not Found - Corrigido
503 - Service Unavailable - Corrigido
