### ISSUE TITLE
Response - acknoweledge Events 

### ISSUE THREAD

**Issue by h2danilo** [Abrasel-Nacional/opendelivery#2]
Olá,

Evento orienta enviar um array com um ou várias Ordens, porém, não tem opção de informar status de cada Ordem no retorno. 

Ex: se envio um ACK com 10 ordens, dessas 8 deram certas e 2 deram erro, não da para informar quais ocorrerão erro e quais deram certas. Seria legal se desse para retornar um array com uma propriedade informando se deu erro ou nao e uma propriedade para escrever uma observação.

![image](https://user-images.githubusercontent.com/38380833/173127243-07afc964-dbc4-4343-86bb-92cb5349d550.png)

**Comment by gui-camargo** [comment]
Olá @h2danilo,

Essa questão foi discutida no comitê técnico e a recomendação foi caso um dos ack esteja com algum problema e não puder ser aceito, então todos os outros também devem ser rejeitados, retornando o código de erro adequado (por exemplo o 400) e indicando no body, qual foi o ack com problema e qual foi o problema. Vamos complementar a documentação com essa recomendação também.
