### ISSUE TITLE
Endpoint de detalhe do pedido - Duvida sobre preenchimento de descontos

### ISSUE THREAD

**Issue by JanaMarinS** [Abrasel-Nacional/opendelivery#20]
No endpoint de detalhes de pedidos: https://abrasel-nacional.github.io/docs/#tag/ordersDetails, há a propriedade de **discounts**, por exemplo se preenchermos os descontos dados no pedido, seja ele no final do pedido de modo global ou individualmente por item, é necessário ainda sim preencher o valor de **discount** que temos no **total**?

**Comment by gui-camargo** [comment]
Olá @JanaMarinS 

A ideia é que a propriedade **discounts** seja utilizada para uma descrição detalhada de todos os descontos que compõem o pedido.
A propriedade **discount** do objeto **total**, é a somatória de todos os descontos que foram detalhados na propriedade **discounts**.

Isso responde sua dúvida?

**Comment by gui-camargo** [comment]
A issue será fechada por falta de novas informações.
