### ISSUE TITLE
Endpoint de detalhe do pedido - Duvida sobre preenchimento de OtherFees

### ISSUE THREAD

**Issue by JanaMarinS** [Abrasel-Nacional/opendelivery#21]
No endpoint de detalhes de pedidos: https://abrasel-nacional.github.io/docs/#tag/ordersDetails, há a propriedade de **otherFees**.
No caso do enum no OtherFees, so tem **marketplace** e **merchant**, no caso da DeliveryCenter (ou de outra logistica) que fique com a taxa neste meio de campo, sera que não faltaria mais um item neste enum? Tipo, Logistica ?

**Comment by gui-camargo** [comment]
Olá @JanaMarinS,

Conforme conversamos no comitê do dia  08/09/2021, iremos acrescentar a opção 'LOGISTIC_SERVICES' no campo **receivedBy** da propriedade **otherFees**.

**Comment by gui-camargo** [comment]
A opção  'LOGISTIC_SERVICES' foi acrescentada na versão rc3.

https://abrasel-nacional.github.io/docs/#tag/ordersDetails

Issue será fechada.
