### ISSUE TITLE
Inclusão de CRC na imageUrl

### ISSUE THREAD

**Issue by rafael-a-guimaraes** [Abrasel-Nacional/opendelivery#22]
No retorno da merchant, seria interessante incluir o crc da imagem no final da imageUrl (ou ainda como um campo separado imageCrc) para evitar que o Marketplace, a cada processamento da estrutura da merchant, faça um novo download desnecessário da imagem para seu repositório quando a imagem não teve alteração, ou, evitar que o Merchant tenha que trocar no nome da imagem para forçar uma atualização no Marketplace ou ainda no browser do usuário final.

**Comment by gui-camargo** [comment]
Olá @rafael-a-guimaraes,

Conforme conversamos no comitê do dia 02/09/2021, irei alterar os campos de imagem da documentação, para que virem um objeto e contenham duas propriedades: URL e CRC.

Exemplo:

Propriedade atual: **logoURL**: string
Nova propriedade: **logo**: object {URL : string, CRC: string}

**Comment by gui-camargo** [comment]
Alterado os atributos de imagens para um objeto do tipo image composto por duas propriedades: URL e CRC
As propriedades alteradas foram:
logoURL no objeto basicInfo do endpoint /merchant para logoImage
bannerURL no objeto basicInfo do endpoint /merchant para bannerImage
imageURL no objeto category do endpoint /merchant para image
imageURL no objeto item do endpoint /merchant para image

Disponível na versão rc3.

Issue será fechada.
