### ISSUE TITLE
Padronização de grafia em alguns campos da merchant

### ISSUE THREAD

**Issue by rafael-a-guimaraes** [Abrasel-Nacional/opendelivery#23]
Não é exatamente um issue mas talvez queiram ajustar.

Na documentação da merchant, o array availabilityId está no singular quando referenciado no objeto Category mas está no plural (availabilityIds) quando referenciado no objeto ItemOffer.

Alguns campos com URL, estão com grafia "Url" e outros com "URL". Exemplo "imageUrl" e "disclaimerURL"

**Comment by gui-camargo** [comment]
Olá @rafael-a-guimaraes,

Obrigado pelas sugestões. Vou ajustar a documentação para termos uma grafia única.

**Comment by gui-camargo** [comment]
A grafia dos campos foi ajustada e disponibilizada na versão rc3.

availabilityIds no objeto itemOffer do endpoint /merchant para availabilityId
optionGroupsIds no objeto itemOffer do endpoint /merchant para optionGroupsId

merchantUrl no endpoint /merchantList para merchantURL
orderUrl no objeto Event utilizado no webhook e no pooling de pedidos para orderURL

Issue será fechada.
