### ISSUE TITLE
Endpoint de detalhe do pedido - Items

### ISSUE THREAD

**Issue by JanaMarinS** [Abrasel-Nacional/opendelivery#25]
No **items** há a prop **totalPrice** para indicar o total do item e na prop de **option** há o **price**, essa prop seria para indiciar também o total visto que existe a propriedade **unitPrice** ? Se sim, ela não deveria chamar **totalPrice** igual ao **items**?

**Comment by gui-camargo** [comment]
Olá @JanaMarinS,
Sim, deveria chamar **totalPrice** igual ao **items**. Vou atualizar a documentação com esta correção.
Obrigado pela contribuição.

**Comment by gui-camargo** [comment]
A nomenclatura do campo price no objeto options do endpoint /orders/{orderId} foi alterada para totalPrice e disponibilizada na versão rc3.

Issue será fechada.
