### ISSUE TITLE
Seção "Total" de Order não está clara

### ISSUE THREAD

**Issue by juliano-sfhera** [Abrasel-Nacional/opendelivery#26]
Analisando a seção "Total" não consegui identificar corretamente ao que refere-se os totais. Em conversa com o Guilherme, o mesmo solicitou que fosse aberta a issue.

"total": {
  "items": 1,
  "otherFees": 5,
  "discount": 0,
  "orderAmount": 55
},

O "Items" segundo o exemplo, seria a quantidade total de itens, porem em conversa com o Guilherme, não é isso.

Segue resposta: "Na verdade agora que eu vi que essa parte do totals ta meio incorreta. 
na verdade todas as propriedades deveriam ser um objeto, (value + currency) igual aos prices"

O questionamento surgiu quando perguntei onde estaria o valor total dos itens do pedido (somente produtos).

Abro esta Issue para que seja discutido este ponto.

**Comment by gui-camargo** [comment]
Conforme discutido em comitê do dia 09/09/2021, os campos de totais e outros campos de valores foram modificados para aceitarem o objeto Price. As mudanças efetuadas foram:

- value no objeto discounts do endpoint /oders/orderid para amount
- todos os atributos da propriedade total do endpoint /orders/{orderid}
  - além disso o nome do atributo items foi alterado para itemsPrice
  
As alterações já estão disponíveis na versão rc3.

Issue será fechada.
