### ISSUE TITLE
Tags para Pedido Agendado "Sheduled Order"

### ISSUE THREAD

**Issue by juliano-sfhera** [Abrasel-Nacional/opendelivery#27]
Não encontramos na API nenhum indicação para pedido agendado, a tag "orderTiming": "INSTANT", que identifica se o pedido é para entrega imediata ou futura, porem nada indicando, caso seja agendado, qual data e hora deve ser entregue.

Sei que talvez não seja foco nesse primeiro momento, mas nós temos agendamento, então teremos que criar algo nosso para quebrar o galho, porém isso pode ser ruim, porque depois nossos parceiros terão que mudar.

Segue modelo do iFood:

"schedule": {
    "deliveryDateTimeStart": "2021-09-17T15:22:28.967Z",
    "deliveryDateTimeEnd": "2021-09-17T15:22:28.967Z"
  }

Eu acho interessante pensar nisso, pois é bem importante.

**Comment by gui-camargo** [comment]
Olá @sfhera.

A pedido agendado bem como a edição de pedidos, não está previsto para a versão de lançamento da API, mas já está no roadmap para as próximas versões, a serem discutidas logo após o lançamento.

Obrigado pela sugestão.

**Comment by gui-camargo** [comment]
A issue será fechada por falta de novas informações.

**Comment by filipesarturi** [comment]
> Não encontramos na API nenhum indicação para pedido agendado, a tag "orderTiming": "INSTANT", que identifica se o pedido é para entrega imediata ou futura, porem nada indicando, caso seja agendado, qual data e hora deve ser entregue.
> 
> Sei que talvez não seja foco nesse primeiro momento, mas nós temos agendamento, então teremos que criar algo nosso para quebrar o galho, porém isso pode ser ruim, porque depois nossos parceiros terão que mudar.
> 
> Segue modelo do iFood:
> 
> "schedule": { "deliveryDateTimeStart": "2021-09-17T15:22:28.967Z", "deliveryDateTimeEnd": "2021-09-17T15:22:28.967Z" }
> 
> Eu acho interessante pensar nisso, pois é bem importante.

Um sugestão de melhoria seria **também** definir o agendamento em cada item do pedido, pois pode ocorrer de certos itens possuírem data/hora de entrega diferentes. Torna a operação mais complexa, pois pode envolver mais de uma entrega, etc... por isso que seria interessante aceitar os dois casos, tanto o agendamento no pedido quanto nos itens.

**Comment by gui-camargo** [comment]
A evolução de pedidos agendados está sendo tratada na issue Abrasel-Nacional/docs#100.

@filipesarturi sobre sua sugestão, vamos colocar no nosso backlog, para uma discussão de evolução para as próximas versões.
