### ISSUE TITLE
Acesso à api

### ISSUE THREAD

**Issue by wallacejesus** [Abrasel-Nacional/opendelivery#28]
Qual será a {baseURL} da api?

Não há nenhuma informação sobre valores. Terá algum custo para consumir a api?

**Comment by gui-camargo** [comment]
Olá @wallacejesus. Tudo bem?

A implementação das APIs (e consequentemente da baseURL) ficará a cargo de cada empresa. O Open Delivery é apenas o padrão para o desenvolvimento das APIs, mas não terá nenhum servidor ou serviço centralizador. 
A ideia é que as empresas adotem o padrão em seus sistemas, e troquem as baseURL e chaves de acesso entre si. 

Sobre a questão do custo, conforme dito acima, o Open Delivery, não é uma plataforma, sistema, aplicativo ou serviço, é apenas a padronização das informações a serem trafegadas nas APIs das plataformas das empresas, então não há custo nenhum para utilização do padrão, bem como a documentação é totalmente aberta.  

Espero ter ajudado.

**Comment by gui-camargo** [comment]
A issue será fechada por falta de novas informações.
