### ISSUE TITLE
serviceArea e serviceAreaFee

### ISSUE THREAD

**Issue by eduardoalmeida** [Abrasel-Nacional/opendelivery#29]
Dentro do objeto Service temos dois atributos: serviceArea e serviceAreaFee. 
Pelo que entendi o serviceArea a área de atuação daquela loja e no serviceAreaFee seriam os valores de frete.

Da meneira que está feito é possível criar regiões desconexas para esses campos (serviceArea centrado em um ponto e serviceAreaFee centrado em um outro ponto).

Acredito que possamos unificar os dois campos para evitar esse problema. Sugestão:
```
"serviceArea": {
  "@id": "22815773000169-01339e6d-520b-429e-bc7c-dcfd2df42278",
  "@type": "SERVICE_AREA",
  "geoRadius": 1000,
  "geoMidpointLatitude": -20.2333,
  "geoMidpointLongitude": -20.8383,
  "fees": [{
    "value": {
      "geoRadius": 300,
      "price": { "value": 5, "currency": "R$" }
    },{
    "value": {
      "geoRadius": 800,
      "price": { "value": 8, "currency": "R$" }
    }{
    "value": {
      "geoRadius": 1000,
      "price": { "value": 10, "currency": "R$" }
    }
  }]
}
```

No caso de utilização de polygon, o fee também poderia utilizar poligonos, algo do tipo
`{
  "polygon": []
  "price": {}
}`

**Comment by gui-camargo** [comment]
Oi @eduardoalmeida,

Obrigado pela sugestão.
Vamos levar a sugestão ao comitê técnico de amanhã.

**Comment by gui-camargo** [comment]
Conforme conversado no comitê do dia 30/09/2021, chegou-se ao consenso de reformular as entidades de serviceArea e serviceAreaFee, juntando as duas e dando mais possibilidades para os poligonos.

Abaixo segue a sugestão de como ficará a entidade serviceArea:

```
"serviceArea": {
        "@id": "22815773000169-01339e6d-520b-429e-bc7c-dcfd2df42278",
        "@type": "SERVICE_AREA",
        "polygon": [ //Passa a ser um array de poligonos
            {
                "geoCord": [ //Ao invés de um conjunto de strings, passa a ser um array de latitudes e longitudes
                    {
                        "latitude": -20.2333,
                        "longitude:": -20.8383
                    }
                ],
                "price": { //Preço passa a ser informado por poligono, juntamente no objeto serviceArea, saindo do serviceAreaFee
                    "value": 8.00,
                    "currency": "BRL"
                }
            }
        ],
        "geoRadius": [ //Contém a distancia máxima de entrega e os preços por distancia (saindo do serviceAreaFee). Obrigatorio informar pelo menos 1 distancia (que será a máxima de entrega)
            {
                "geoMidpointLatitude": -20.2333,
                "geoMidpointLongitude": -20.8383,
                "radius": [
                    {
                        "size": 100, // até 100 metros considera este valor
                        "price": { 
                            "value": 8.00,
                            "currency": "BRL"
                        }
                    },
                    {
                        "size": 300, //até 300 metros considera esse valor
                        "price": {
                            "value": 10.00,
                            "currency": "BRL"
                        }
                    },
                    {
                        "size": 5000, //até 5km considera este valor e também a distancia máxima de entrega.
                        "price": { 
                            "value": 15.00,
                            "currency": "BRL"
                        }
                    }       
                ]
            }
        ]
    }
```

Essa issue ficará aberta até o próximo comite, aberta para comentários e sugestões e será rediscutida no comite do dia 07/10/2021.

**Comment by gui-camargo** [comment]
A sugestão foi adotada juntamente com as sugestões das issues relacionadas na versão rc5.
Changelog oficial:
* [[Issues Abrasel-Nacional/docs#29](https://github.com/Abrasel-Nacional/docs/issues/29) | [#20](https://github.com/Abrasel-Nacional/docs/issues/30) | [ Abrasel-Nacional/docs#37](https://github.com/Abrasel-Nacional/docs/issues/37) | [ Abrasel-Nacional/docs#43](https://github.com/Abrasel-Nacional/docs/issues/43)] - Reformulação de toda a estrutura da entidade `SERVICE_AREA`. Os campos da entidade receberam uma nova estrutura facilitando o cadastro, bem como integrando a parte de taxas e distancia de entrega. Com isso a entidade `SERVICE_AREA_FEE` foi excluída da documentação pois sua função foi incorporada na 'SERVICE_AREA`.

	A nova estrutura pode ser conferida na documentação: https://abrasel-nacional.github.io/docs/#section/Service
