### ISSUE TITLE
Esclarecimento e alguns questionamentos sobre o fluxo de pedidos segundo diagrama OD.

### ISSUE THREAD

**Issue by symonlopes** [Abrasel-Nacional/opendelivery#3]
Olá pessoal, 

Temos alguns questionamentos sobre os últimos passos no fluxo de processamento de pedido:

![image](https://user-images.githubusercontent.com/781975/178048761-7953da54-7694-4abd-ac11-858d0f6bc209.png)

A maior parte são confirmações sobre o nosso entendimento desse fluxo. Merchant/EC e SOFTWARE SERVICE são o mesmo player no texto.

1. Entendemos que o evento READY_FOR_PICKUP deve ser disparado independentemente do pedido ser do tipo DELIVERY ou TAKEOUT, está correto?
2.  Entendemos que o evento DISPATCHED deve ser disparado mesmo quando o pedido é do tipo TAKEOUT? Nesse tipo de pedido, em que momento o merchant dispararia esse evento? Seria no momento que o CUSTOMER retira o pedido?
3. Pedidos do tipo TAKEOUT se dividem em dois tipos: DEFAULT ou PICKUP_AREA que, segundo nosso entendimento seria: DEFAULT: Retirada por padrão no endereço estabelecimento.
PICKUP_AREA: Quando o pedido for desse tipo, um evento do tipo PICKUP_AREA_ASSIGNED deve ser disparado em determinado momento definindo o local de retirada do pedido. Esse mesmo evento de PICKUP_AREA_ASSIGNED, possui um campo chamado **metadata.pickupArea** descrevendo o local de retirada do pedido. O meu questionamento aqui é: o ponto de retirada do pedido não deveria ser definido pelo merchant? De acordo com o diagrama, esse evento é criado e retornado pelo pela ORDERING APPLICATION, do lado do CUSTOMER. Não estou entendendo como essa informação seria fornecida por esse player no sistema.
6. O evento de CONCLUDED é disparado automaticamente pela ORDERING APPLICATION em um pedido de DELIVERY logo após a emissão do evento de DISPATCHED?
7.  É correto afirmar que em nenhum cenário o evento de CONCLUDED é gerado pelo EC? Nos pedidos do tipo TAKEOUT, dá pra entender que no momento em que o CUSTOMER retira o pedido do merchant, faz sentido marcar o pedido como CONCLUDED. Porém, em um pedido de DELIVERY, o DISPATCHED indicaria somente que o pedido saiu para entrega certo? Ou seja, nesse cenário de DELIVERY o pedido só seria concluído quando o CUSTOMER confirmasse que recebeu o pedido. Após essa confirmação a ORDERING APPLICATION dispararia um evento de CONCLUDED que seria consumido posteriormente pelo merchant no SOFTWARE SERVICE.
8. A implementação do evento do tipo PICKUP_AREA_ASSIGNED é opcional, está correto? Podemos implementar o modo DEFAULT de pedidos TAKEOUT, por exemplo.

Desde já, muito obrigado!

**Comment by gui-camargo** [comment]
Olá @symonlopes 

Respostas abaixo:

> 1. Entendemos que o evento READY_FOR_PICKUP deve ser disparado independentemente do pedido ser do tipo DELIVERY ou TAKEOUT, está correto?

Ele é sempre obrigatório para o tipo TAKEOUT, mas não necessariamente precisaria ser enviado para o tipo DELIVERY. Podemos levantar essa discussão no próximo comite, para ver se colocamos alguma obrigatoriedade, ou não quanto a esse campo.

> 2. Entendemos que o evento DISPATCHED deve ser disparado mesmo quando o pedido é do tipo TAKEOUT? Nesse tipo de pedido, em que momento o merchant dispararia esse evento? Seria no momento que o CUSTOMER retira o pedido?

Ele deve ser disparado apenas para o DELIVERY. 

Vamos conversar no comitê, para talvez deixar mais claro no fluxo, quando enviar cada evento.

> 3. Pedidos do tipo TAKEOUT se dividem em dois tipos: DEFAULT ou PICKUP_AREA que, segundo nosso entendimento seria: DEFAULT: Retirada por padrão no endereço estabelecimento.
PICKUP_AREA: Quando o pedido for desse tipo, um evento do tipo PICKUP_AREA_ASSIGNED deve ser disparado em determinado momento definindo o local de retirada do pedido. Esse mesmo evento de PICKUP_AREA_ASSIGNED, possui um campo chamado metadata.pickupArea descrevendo o local de retirada do pedido. O meu questionamento aqui é: o ponto de retirada do pedido não deveria ser definido pelo merchant? De acordo com o diagrama, esse evento é criado e retornado pelo pela ORDERING APPLICATION, do lado do CUSTOMER. Não estou entendendo como essa informação seria fornecida por esse player no sistema.

O entendimento está correto, mas sobre o PICKUP_AREA, na verdade quem vai definir isso é o consumidor, digitando através do aplicativo do ORDERING APPLICATION. Imagina o cenário que você pede um TAKEOUT em um shopping, mas quer receber o pedido no estacionamento. Neste caso o consumidor digita no app (que por sua vez, preenche o metadata.pickupArea) qual a vaga que ele está (exemplo 2A). Por isso no fluxo é o ORDERING APPLICATION quem manda para o SOFTWARE.

 > 4. O evento de CONCLUDED é disparado automaticamente pela ORDERING APPLICATION em um pedido de DELIVERY logo após a emissão do evento de DISPATCHED?
 
Ele deve ser disparado quando vocês finalizarem o pedido na plataforma de vocês.

> 5. É correto afirmar que em nenhum cenário o evento de CONCLUDED é gerado pelo EC? Nos pedidos do tipo TAKEOUT, dá pra entender que no momento em que o CUSTOMER retira o pedido do merchant, faz sentido marcar o pedido como CONCLUDED. Porém, em um pedido de DELIVERY, o DISPATCHED indicaria somente que o pedido saiu para entrega certo? Ou seja, nesse cenário de DELIVERY o pedido só seria concluído quando o CUSTOMER confirmasse que recebeu o pedido. Após essa confirmação a ORDERING APPLICATION dispararia um evento de CONCLUDED que seria consumido posteriormente pelo merchant no SOFTWARE SERVICE.

Sim, para encerrar o pedido, o ORDERING APPLICATION, precisaria receber uma indicação de concluido, ou pelo consumidor ou pela entregador, mas de qualquer maneira, isso seria pela plataforma do ORDERING APPLICATION. 
Temos no backlog do projeto uma evolução para criar uma rota para o EC finalizar o pedido, mas ainda não a discutimos.

> 6. A implementação do evento do tipo PICKUP_AREA_ASSIGNED é opcional, está correto? Podemos implementar o modo DEFAULT de pedidos TAKEOUT, por exemplo.

Sim, é opcional.

Peço que se possível participem do próximo comite técnico (dia 14/07/2022) onde além de discutir esses pontos, vamos fazer um review das evoluções que irão entrar na versão 1.0.1 no dia 01/08/2022

**Comment by gui-camargo** [comment]
Olá @symonlopes 

Refiz os gráficos dos fluxos para melhor entendimento. 

![image](https://user-images.githubusercontent.com/80956588/182870057-b1ae07b2-73ff-4147-a2e7-5ab5cbfa1e49.png)

![image](https://user-images.githubusercontent.com/80956588/182870092-8a38e425-e9ae-4a9d-b9d2-855b7115ea90.png)

A documentação já está atualziada.
