### ISSUE TITLE
Arrumar exemplo e melhorar documentação do campo polygon dentro do serviceArea

### ISSUE THREAD

**Issue by eduardoalmeida** [Abrasel-Nacional/opendelivery#30]
Atualmente a documentação desse campo diz que é "a series of three or more space delimited points" mas não diz o formato de cada ponto. No exemplo está apenas uma lista de strings.

Sugestão:
```
"polygon": [
  {"latitude": 0.0, "longitude": 0.0},
  {"latitude": 0.0, "longitude": 0.0},
  {"latitude": 0.0, "longitude": 0.0}
]
```

**Comment by gui-camargo** [comment]
Está sendo tratada na issue Abrasel-Nacional/docs#29
