### ISSUE TITLE
[LINX] Adicionar campo Id ou cnpj da loja para indicar de qual loja está enviando o pedido via  webhook. 

### ISSUE THREAD

**Issue by Palharim** [Abrasel-Nacional/opendelivery#31]
Estamos desenvolvendo via web hook.
O marketplace envia o pedido para nós e salvamos as informações em nossa base. Mas como o token é por loja, é preciso adicionar um campo identificador único ou CNPJ da loja na request do webhook para poder identificar qual loja eu devo gerar o token para buscar o detalhe do pedido. 

![image](https://user-images.githubusercontent.com/91553139/135116865-fb8d953d-b81e-491c-85ee-b7afdc94f6ba.png)
![image](https://user-images.githubusercontent.com/91553139/135116916-18b7a088-b00b-4776-b0b7-e425cd36e868.png)

**Comment by eduardoalmeida** [comment]
Eu não havia entendido que o token seria por loja. Acredito que a ideia é que o token seja uma autenticação do "POS" no "Marketplace". Dessa forma, tendo o token por Marketplace e o orderId no evento daria para consultar os detalhes do pedido e lá teria o merchant.
Na descrição do método de polling:
"Polls events for any orders from merchants associated with the authenticated user". Então acredito que o token seja para o sistema inteiro e não para uma loja específica.

**Comment by gui-camargo** [comment]
Olá @eduardoalmeida e @Palharim ,

No ultimo comite do dia 23/09/2021, surgiu a duvida se as credenciais seriam por sistema (aplicação) ou por merchant. Inicialmente realmente estavamos pensando em aplicação conforme o @eduardoalmeida comentou, mas depois do comite foi decidido que seria melhor por merchant mesmo, para evitar acessos indevidos por parte dos serviços de software.

Amanhã (30/09/2021) no comitê vamos fechar esse tema, convido os dois a contribuírem mais no assunto.

**Comment by gui-camargo** [comment]
Conforme discutido no comite do dia 30/09/2021 foi efetuada a Inclusão do atributo **X-App-MerchanId** como parametro de **header** no request do webhook de notificação de pedido (/orderEvent) com o intuito de identificar qual merchant está recebendo o pedido.

Disponível na versão rc4.
