### ISSUE TITLE
Get Access Token

### ISSUE THREAD

**Issue by eduardoalmeida** [Abrasel-Nacional/opendelivery#32]
Por recomendação, o método HTTP GET não deveria ter body. O Get Access Token (https://abrasel-nacional.github.io/docs/#operation/getToken) utiliza o GET e Body.
Sugestão: trocar o método para POST

Na documentação no campo grantType o value está como "clientCredentials" e na descrição está como "client_credentials".

**Comment by gui-camargo** [comment]
Conforme discutido no comitê do dia 30/09/2021 as seguintes alterações foram feitas:

- Corrigido o endpoint de autenticação `/oauth/token` para **`POST`** . Estava incorretamente descrito como `GET`.
- Corrigida a opção do atributo `grantType` do endpoint `oauth/token` de `clientCredentials` para `client_credentials`.

Disponível na versão rc4.
