### ISSUE TITLE
Exemplo e documentação do campo discounts do objeto Order

### ISSUE THREAD

**Issue by eduardoalmeida** [Abrasel-Nacional/opendelivery#33]
Na documentação, o objeto que representa um desconto tem um campo chamado "amount" mas no exemplo está como "value".
A documentação do campo "sponsorshipValues" diz ser um Array mas no exemplo está um único objeto.
Dentro de cada sponsorshipValue, na documentação tem o campo "amount" e no exemplo "value".

Sugestão: trocar a documentação de amount para value (para ficar igual os prices e os payments)

**Comment by gui-camargo** [comment]
Olá @eduardoalmeida,

Obrigado pela sugestão. 
Como envolve troca de nome de campo, vamos levar para discussão no comitê do dia 07/10/2021.

**Comment by gui-camargo** [comment]
O exemplo foi ajustado para refletir o nome dos campos corretamente.

![image](https://user-images.githubusercontent.com/80956588/137659424-11f5b758-cea7-4100-90a6-371997377f3d.png)
