### ISSUE TITLE
estimatedDeliveryDateTime e deliveryDateTime no campo delivery do objeto order

### ISSUE THREAD

**Issue by eduardoalmeida** [Abrasel-Nacional/opendelivery#34]
Deixar mais claro na documentação para que serve cada um desses campos e qual a diferença entre eles. Talvez os dois deveriam ser um campo só?

Na documentação o estimatedDeliveryDateTime está como "required" mas ele não está presente no exemplo. No exemplo existe o campo deliveryDateTime dentro do objeto address.

**Comment by gui-camargo** [comment]
Olá @eduardoalmeida,

A Ideia é que o **estimatedDeliveryDateTime** fosse a data hora estimada da entrega e o **deliveryDateTime**  a hora realmente que a entrega foi efetuada (esse campo viria nulo enquanto a mesma não fosse realizada).

Podemos discutir melhor no próximo comitê.

Sobre o exemplo. irei corrigir.

**Comment by gui-camargo** [comment]
Descrições e exemplos foram ajustados para melhor refletir a intenção dos campos.

![image](https://user-images.githubusercontent.com/80956588/137660001-de421247-a3a8-4dcd-bb43-92b2006c6410.png)

![image](https://user-images.githubusercontent.com/80956588/137660023-80c73a5e-ac8d-40fb-ab12-671db32f7103.png)
