### ISSUE TITLE
Seprar documentação 

### ISSUE THREAD

**Issue by marcoaureliotw2** [Abrasel-Nacional/opendelivery#35]
Seria interessante separar a documentação, uma voltada para Ordering Application e outra para Software Service. Creio que ficaria mais claro e facil de entender o padrão.

**Comment by gui-camargo** [comment]
Olá @marcoaureliotw2 obrigado pela sugestão..

Vamos levar a sugestão para o comitê técnico, mas na versão rc4 disponibilizada hoje (04/10/2021), foi inserido em todos os endpoints qual o HOST e a DIREÇÃO do endpoint.

Peço que dê uma olhada e veja se ficou mais claro desta maneira.

**Comment by gui-camargo** [comment]
A issue foi discutida no comitê do dia 07/10/2021 e os membros concordaram em manter a documentação no formato atual, pois é importante que as duas partes conheçam todas as APIs, pois de qualquer maneira as duas partes vão precisar saber ou enviar ou receber as informações dos endpoints.
