### ISSUE TITLE
Campo troco ao detalhe do pedido

### ISSUE THREAD

**Issue by hubdelivery** [Abrasel-Nacional/opendelivery#36]
Adicionar o campo "troco" no nó de payments para indicar o quanto de troco o lojista tem que se organizar para pagamentos na entrega.

**Comment by gui-camargo** [comment]
Olá @hubdelivery,

O campo de troco já está disponível na documentação:
![image](https://user-images.githubusercontent.com/80956588/136966550-24906a67-7469-478e-89ab-d948cc6afcb7.png)

Ele não está no exemplo pois não é obrigatório.
Mas estou revisando todos os exemplos de todas entidades, e vou procurar colocar esses campos não obrigatórios também.
