### ISSUE TITLE
Adicionar estimativa de tempo de entrega / retirada à ServiceAreaFee

### ISSUE THREAD

**Issue by hubdelivery** [Abrasel-Nacional/opendelivery#37]
Adicionar campo com a estimativa de tempo (em minutos) de entrega / retirada ao objeto ServiceAreaFee.

**Comment by gui-camargo** [comment]
Conforme discutido no comitê do dia 7/10/2021 a sugestão foi acatada e está disponível na nova estrutura do serviceArea.
Essa issue será incorporada a issue Abrasel-Nacional/docs#29  onde estão sendo tratada todas as alterações da entidade serviceArea.
