### ISSUE TITLE
Campo "allergen" com array duplicado de strings na estrutura de um Item

### ISSUE THREAD

**Issue by brayannluiz** [Abrasel-Nacional/opendelivery#38]
No nó de um item do menu, o campo "allergen" consta como um array de um array de strings. Acredito que o correto seja somente um array de strings.

`{
  "@id": "22815773000169-732bd31e-77fc-47ee-88ee-a0437f97b198",
  "@type": "ITEM",
  "name": "1/2 Pepperoni",
  "description": "Pepperoni flavored pizza with LOTS of pepperoni.",
  "externalCode": "23",
  "image": "https://www.food-place.com/images/peperroni.png",
  "nutritionalInfo": {
    "description": "Contains preservatives",
    "calories": "2000 Cal",
    "allergen": [
      [
        "GLUTEN"
      ]
    ],
    "additives": [
      "string"
    ],
    "suitableDiet": [
      "DIABETIC"
    ],
    "isAlcoholic": "string"
  },
  "serving": 0,
  "unit": "0",
  "ean": "string"
}`

Para referência:
https://abrasel-nacional.github.io/docs/#section/Menu/Item

**Comment by gui-camargo** [comment]
Olá @brayannluiz 

O campo está descrito de forma errada no exemplo, mas na descrição do objeto está correto:

![image](https://user-images.githubusercontent.com/80956588/136966992-0ba98cae-714a-48ec-831a-f26a54f56489.png)

Estou revisando os exemplos e irei arrumar este campo.

**Comment by gui-camargo** [comment]
Campo corrigido no exemplo.

![image](https://user-images.githubusercontent.com/80956588/137660310-28b33a06-52e6-4923-ac23-144056b7a3d9.png)
