### ISSUE TITLE
Converter campos que se iniciam com "is" para boolean (true/false)

### ISSUE THREAD

**Issue by brayannluiz** [Abrasel-Nacional/opendelivery#39]
Por padrão, sugiro manter quaisquer campos que se iniciem com "is" como flags boolean (true/false). Temos um campo hoje chamado "isAlcoholic" definido como string em um item do menu. 

Para referência: 
https://abrasel-nacional.github.io/docs/#section/Menu/Item

**Comment by gui-camargo** [comment]
Olá @brayannluiz 

O campo foi modificado para **boolean** e está disponível na versão rc5.
No momento só temos este campos iniciando por "is".
