### ISSUE TITLE
Documentação Versão Beta Modificada

### ISSUE THREAD

**Issue by boydwo** [Abrasel-Nacional/opendelivery#4]
Olá,
Sou desenvolvedor da QUIQ e utilizamos OD para fazer a originação de pedidos com outras plataformas que também estão implementando o protocolo.

Iniciamos a utilização do protocolo OD em meados de janeiro/fevereiro de 2022, até então havia apenas a versão BETA, por isso todos os nosso integradores até este momento estão utilizando a versão BETA implementada. Porém, após o lançamento da V1 a documentção da versão BETA também foi atualizada. E alguns campos foram modificados prejudicando a integração das plataformas. Em GetOrderDetails  -> delivery -> deliveryAddress os campos: 
street, number, district que antes chamavam streetName, streetNumber, neighborhood.

Por acaso, poderiam manter a documentação da versão beta como foi concebida ou era utilizada no inicio do projeto?

Além disso, é possivel descrever detalhadamente cada novo changelog?
Para termos uma ideia de tudo que mudou, pois hoje temos uma aplicação robusta e já está utilizando o protocolo em produção com varios integradores e ainda não temos noção de todas as mudanças que foram feitas da BETA para V1, estamos descobrindo agora com a chegada de novos integradores que estão utilizando as novas docs do OD e estão enfretando erros. Logo, toda nova versão precisaremos estudar cuidadosamente formas de se atualizar e tendo um changelog descritivo nos ajudará a acompanhar e sermos mais assertivos nas atulizações e nas evoluções do nosso produto.

**Comment by gui-camargo** [comment]
Olá @boydwo, 

A versão Beta tem como caracter a possibilidade de modificações a qualquer momento.
Estes campos que você citou foram alterados antes de efetuarmos o corte para a versão de release.

O changelog completo antes de efetuarmos o release (1.0.0) pode ser encontrado aqui:
https://github.com/Abrasel-Nacional/Open-Delivery-Beta-Test/blob/main/CHANGELOG.md

O changelog pós release (1.0.1-rcx) se encontra na própria documentação, na seção Changelog:
https://abrasel-nacional.github.io/docs/beta/#tag/versionChangelog

Como não sabemos a partir de qual data vocês iniciaram o desenvolvimento, não consigo disponibilizar exatamente a versão que vocês utilizaram (tivemos 13 release candidates na versão Beta).

Aconselho a vocês atualizarem a API para a versão release, para conseguir sempre atender as empresas entrantes.
Soltamos agora a versão 1.0.1, mas é possível acessar a versão anterior:

Versão 1.0.1 - https://abrasel-nacional.github.io/docs/
Versão 1.0.0 - https://abrasel-nacional.github.io/docs/versions/1.0.0/

**Comment by gui-camargo** [comment]
Fechando a issue por falta de novos pontos.
