### ISSUE TITLE
Renomear a propriedade "availability" do Merchant para "availabilities"

### ISSUE THREAD

**Issue by brayannluiz** [Abrasel-Nacional/opendelivery#40]
Como sugestão, buscando o padrão do restante do projeto, sugiro renomear a propriedade "availability" para "availabilities" na estrutura do Merchant já que a mesma se trata de um array de objetos "availability".

Para referência:
https://abrasel-nacional.github.io/docs/#tag/merchantStructure

**Comment by gui-camargo** [comment]
Olá @brayannluiz 

A mudança do campo foi discutida no comitê do dia 07/10/2021 e foi acatada.
Foi alterada na versão rc5 e já está disponível.

![image](https://user-images.githubusercontent.com/80956588/136968137-ffc367ed-fa6b-461a-a776-4d5b2250e173.png)
