### ISSUE TITLE
Renomear a propriedade "category" do Merchant para "categories"

### ISSUE THREAD

**Issue by brayannluiz** [Abrasel-Nacional/opendelivery#41]
Como sugestão, buscando o padrão do restante do projeto, sugiro renomear a propriedade "category" para "categories" na estrutura do Merchant já que a mesma se trata de um array de objetos "category".

Para referência:
https://abrasel-nacional.github.io/docs/#tag/merchantStructure

**Comment by gui-camargo** [comment]
Olá @brayannluiz 

A campo de categoria já estava no plural, mas o exemplo estava incorreto.

![image](https://user-images.githubusercontent.com/80956588/136968308-ee9409d6-4603-4c60-a1cc-798eee6f994a.png)

Fiz o ajuste no exemplo também:
![image](https://user-images.githubusercontent.com/80956588/136968372-e753ffa2-149c-428c-ad3b-b7237f1c6aa1.png)
