### ISSUE TITLE
Endpoint de detalhe do pedido -  campos com @ na frente

### ISSUE THREAD

**Issue by JanaMarinS** [Abrasel-Nacional/opendelivery#42]
Na documentação as especificações dos campos, as props de **id** por exemplo estão com **@** na frente(**@id**), porém no exemplo ao lado não tem o **@** nesses campos. Qual é a forma correta de retornar esses campos, é com **@** na frente ou sem ele? Abaixo exemplo das props que estão assim:

![Captura de tela de 2021-10-06 15-54-53](https://user-images.githubusercontent.com/43681114/136265598-b0340844-eef8-4920-a287-10ec51de85c1.png)

**Comment by gui-camargo** [comment]
Olá @JanaMarinS 

O campo deve ser usado com o @ na frente.
O exemplo está incorreto e será corrigido.

**Comment by hubdelivery** [comment]
@gui-camargo qual a motivação para essa definição?
Não seria mais simples a definição do formato Json sem esses "@" em alguns campos e outros não?

**Comment by gui-camargo** [comment]
Olá @JanaMarinS 

Ontem no comite técnico nós conversamos sobre esse assunto e decidimos remover o @ de todos os campos id e vamos também tirar o campo type de algumas entidades do merchant.

Então para o pedido, considere que os campos @id e @type vão ser alterados para id e type.

**Comment by gui-camargo** [comment]
Conforme discutido no comite técnico do dia 14/10/2021 a documentação foi alterada:

  - Removido todos os `@` da frente dos atributos `@id`. Agora todos os atributos estão padronizados como `id`.  
  - Removido todos os campos `@type` das entidades do `/merchant`.
  - Removido o `@` do atributo `@type` do objeto `orders` que foi renomeado para `type` (sem o @).
![image](https://user-images.githubusercontent.com/80956588/137760918-3f3185b8-0696-4060-ab86-87b6ba05eb39.png)

Já disponível na versão rc6.
