### ISSUE TITLE
Explicação sobre : serviceArea X serviceAreaFee

### ISSUE THREAD

**Issue by eduardomrj** [Abrasel-Nacional/opendelivery#43]
Olá,

No que entendi na documentação, "serviceArea" define a área onde poderá ser feita a entrega, ok.
No "serviceAreaFee", defino a taxa de entrega de uma determinada sub-área contida no serviceArea ?
Se sim, existe um problema.
No ServiceArea eu poso definir polígonos já no serviceAreaFee não existe essa opção.

Uma imagem do exemplo.
![Captura de Tela 2021-10-06 às 19 50 50](https://user-images.githubusercontent.com/13318017/136294502-ca37d2e2-f2aa-4b8b-a8ac-0649175de930.png)

Como posse resolver esse tipo de situação ?

**Comment by gui-camargo** [comment]
Olá @eduardomrj,

A seção de serviceArea foi reestruturada conforme conversas do comitê do dia 07/10/2021.
Para outras dúvidas a respeito do serviceArea, por favor continuar a discussão na issue Abrasel-Nacional/docs#29 .
