### ISSUE TITLE
Dúvida : TAKEOUT e DELIVERY

### ISSUE THREAD

**Issue by eduardomrj** [Abrasel-Nacional/opendelivery#44]
Quando houver retirada e delivery deve ser enviado um array como mostrado abaixo ? como fazer?

[
{"@id": "22815773000169-f078e8e2-3044-4eec-b4a8-8359810de123",
"@type": "SERVICE",
"status": "AVAILABLE",
"serviceType": "DELIVERY",
"menuId": "22815773000169-f627ccdc-6789-456f-a782-148538d5035b",
"serviceArea": {},
"serviceAreaFee": {},
"serviceHours": {}
},
{
"@id": "22815773000169-12fd21e11d3-3044-4eec-b4a8-213421211f21",
"@type": "SERVICE",
"status": "AVAILABLE",
"serviceType": "TAKEOUT",
"menuId": "22815773000169-f627ccdc-6789-456f-a782-148538d5035b",
"serviceArea": {},
"serviceAreaFee": {},
"serviceHours": {}
}
]

**Comment by gui-camargo** [comment]
Olá @eduardomrj 

Sim, deve ser usado desta maneira.

Posso ajudar em algo mais?

**Comment by eduardomrj** [comment]
Entendido, obrigado.
