### ISSUE TITLE
Ajustar a nomenclatura X-App-MerchantId no Webhook Order Event Notification

### ISSUE THREAD

**Issue by hubdelivery** [Abrasel-Nacional/opendelivery#45]
Ajustar a nomenclatura X-App-MerchantId na documentação do Webhook Order Event Notification.

![image](https://user-images.githubusercontent.com/91287812/136440925-9a0a555e-c2f1-401f-a9bd-49f35dcdc4b5.png)

**Comment by gui-camargo** [comment]
Olá @hubdelivery 

Este foi o nome que foi discutido no comitê. Qual seria a sugestão de correção?

**Comment by hubdelivery** [comment]
@gui-camargo,  a nomenclatura está correta, mas a grafia não.

Está faltando o T ao X-App-Merchan**t**Id

**Comment by gui-camargo** [comment]
A nomenclatura foi ajustada.
Está disponível na versão rc6.
