### ISSUE TITLE
Adicionar Time Zone aos dados do merchant

### ISSUE THREAD

**Issue by hubdelivery** [Abrasel-Nacional/opendelivery#46]
Adicionar o Time do Merchant ao BasicInfo do merchant.

**Comment by gui-camargo** [comment]
Olá @hubdelivery 

Obrigado pela sugestão. Será discutida no próximo comitê. Peço que se possível participe.

Apenas para ver se eu entendi, seria um campo integer, onde seria preenchido em qual time zone o merchant trabalha? Por exemplo para os merchants em horário de Brasilia seria preenchido com "-3"?

**Comment by hubdelivery** [comment]
@gui-camargo, a idéia que se fosse um campo texto como no exemplo abaixo

`"timeZone": "E. South America Standard Time"`

**Comment by gui-camargo** [comment]
Conforme discutido no comitê do dia 14/10/2021, o timezone deverá ser informado juntamente com a data, utilizando o time-offset do UTC.

Exemplo:
**2021-10-18T14:53:00-03:00**
