### ISSUE TITLE
Padronização de datas em formato UTC

### ISSUE THREAD

**Issue by hubdelivery** [Abrasel-Nacional/opendelivery#47]
Sugestão padronizar todas as datas em formato UTC

**Comment by gui-camargo** [comment]
Olá @hubdelivery.

Este assunto foi tratado na issue Abrasel-Nacional/docs#16 e na documentação está descrito o formato de utilização (que é baseado no UTC):

![image](https://user-images.githubusercontent.com/80956588/136969621-b6796267-b3cc-4f92-8685-25c88ae07196.png)

Existe algum lugar na documentação que não está utilizando este padrão?

**Comment by hubdelivery** [comment]
A idéia é que as datas sejam todas em UTC.. não somente no formato UTC.

Com essa mudança, o orderning application e software services podem aplicar a conversão de data conforme o timezone do merchant

**Comment by gui-camargo** [comment]
Este assunto será tratado na issue Abrasel-Nacional/docs#46 .
