### ISSUE TITLE
Implementar autenticação no endpoint repository

### ISSUE THREAD

**Issue by hubdelivery** [Abrasel-Nacional/opendelivery#48]
Implementar um padrão de autenticação para o endpoint /repository

**Comment by gui-camargo** [comment]
Olá @hubdelivery 

Este endpoint necessita ser discutido melhor, pois provavelmente será depreciado.
Vamos levar este assunto para o comitê do dia 14/10/2021.

Peço que se possível participe.

**Comment by hubdelivery** [comment]
Excelente, muito obrigado pelo posicionamento

**Comment by gui-camargo** [comment]
O endpoint foi removido da documentação e não será mais utilizado.
