### ISSUE TITLE
Erro de definição de status na documentação (/orders)

### ISSUE THREAD

**Issue by luizbaldancaD** [Abrasel-Nacional/opendelivery#49]
Nos seguintes endpoint abaixo no status 200 está descrito como Accepted:
/orders/{orderId}/readyForPickup
/orders/{orderId}/dispatch

Nesse caso seria 200 (OK) ou 202 (Accepted)?

**Comment by gui-camargo** [comment]
Olá @luizbaldancaD,

Conforme conversado no comitê do dia 14/10/2021, o correto é o 202 - Accepted.

Na versão rc6 foi corrigido para o 202 os seguintes endpoints:
  - `/orders/{orderId}/confirm`
  - `/orders/{orderId}/requestCancellation`
  - `/orders/{orderId}/readyForPickup`
  - `/orders/{orderId}/dispatch`
