### ISSUE TITLE
[e-Deploy] - Tratamento de Repetição de eventos do pedido

### ISSUE THREAD

**Issue by eduardoalmeida** [Abrasel-Nacional/opendelivery#5]
Durante a integração com a QUIQ surgiu a seguinte situação:
Ao tratar um evento de CONFIRMED aconteceu um problema e o pedido não foi atualizado corretamente na base de dados. O sistema da e-Deploy começou a retentar a confirmação chamando a API de confirm "/v1/orders/{orderId}/confirm". O sistema da QUIQ, como já havia recebido o ACK de um evento de CONFIRMED passado, não colocou um outro no polling.
A dúvida é: o sistema da e-Deploy assumiu que, toda vez que a API de confirm for chamada, haverá um evento de CONFIRMED correspondente no polling. O sistema da QUIQ assumiu que ao dar ACK em um evento de CONFIRMED de um pedido, o processo já aconteceu e não é necessário colocar outro CONFIRMED no polling.
As duas interpretações estão corretas ao meu ver. Precisamos definir uma como a correta para tratamento desse caso.
Recentemente adicionamos o 422 na resposta das APIs de atualização de eventos, talvez possamos usar isso para resolver o problema.

**Comment by gui-camargo** [comment]
Olá @eduardoalmeida,

Esta issue acabou ficando aberta mas a discussão já ocorreu nos comites.

Conforme foi conversado, foi adicionado um trecho na documentação com orientações em como tratar as duplicidades de eventos:

![image](https://user-images.githubusercontent.com/80956588/199074764-f6383a3f-eef5-4926-8048-c1a5868dbf6e.png)

Vou fechar a issue, mas se tiver mas alguma dúvida pode reabri-la.
