### ISSUE TITLE
Problema de segurança

### ISSUE THREAD

**Issue by luizbaldancaD** [Abrasel-Nacional/opendelivery#50]
Como garantimos que o orderId enviado no payload de uma request, por exemplo no endpoint (/orders/{orderId}/dispatch), está autorizado a fazer a mudar o status da order?
Se ele não estiver autorizado a mexer naquela order, devo retornar um 403?
Não há nada que garanta no fluxo atual que o orderId pertence ao estabelecimento vinculado com o token OAuth2 gerado para aquele estabelecimento.

Possíveis soluções:
- Mudar o enpoint para /orders/{merchantId}/{orderId}/dispatch
- Mandar no payload o merchantId

Observação:
Essas perguntas só se tornam válidas em um fluxo de micro-serviços com o processamento assíncrono.

**Comment by gui-camargo** [comment]
Olá @luizbaldancaD 

Como é a Ordering Application quem gera o pedido e o token pro estabelecimento, ela saberia a qual merchant aquele pedido pertence e se o token informado é daquele estabelecimento. Por isso foi entendido que não era necessário enviar o merchantId, pois o orderId sempre seria para um merchant especifico exclusivamente.

Sobre as sugestões, vamos levar para discutir em comitê, e se facilitar o fluxo podemos colocar no padrão. Peço que se possível participe do comite do dia 14/10/2021 onde será discutida.

**Comment by hubdelivery** [comment]
@luizbaldancaD , acreditamos que essa validação seja feita diretamente no escopo do Ordening Application, não necessitando da segmentação do endpoint para a validação.

**Comment by gui-camargo** [comment]
Olá @luizbaldancaD ,

Conforme conversado no comitê do dia 14/10/2021, o endpoint irá retornar um 403 caso não reconheça a chave de acesso.
Para os casos onde a chave for aceita, mas não corresponder ao merchant da order, o endpoint irá retornar o 202, mas o software Service não irá receber o evento de confirmação no pooling ou webhook na sequencia.
