### ISSUE TITLE
[LINX] - Criação de um novo status.

### ISSUE THREAD

**Issue by Palharim** [Abrasel-Nacional/opendelivery#51]
Sentimos a necessidade da criação de um status (chamado Failure) com o objetivo de alertar o marketplace sobre pedido que o PDV apresentou falha ao resgatar.
Exemplos: itens não cadastrados, divergência no pagamento, falha de produto e etc.

![image](https://user-images.githubusercontent.com/91553139/138292057-c6c1aa5e-7103-4033-ac2b-2501711568a8.png)

![image](https://user-images.githubusercontent.com/91553139/138291643-f7799e67-2018-4ef9-8e57-f405fda63659.png)

O corpo dessa requisição poderia ser um:
Reason como required
FailureCode como opcional

**Comment by gui-camargo** [comment]
Olá @Palharim 

A Ideia seria usar o fluxo de cancelamento para esses casos, informando o code e a reason:
![image](https://user-images.githubusercontent.com/80956588/138692083-194b43ad-8332-4b07-ac4b-1e931f7b0b6a.png)

Podemos levar para a discução no comite é necessário realmente um fluxo especifico para este caso, mas a ideia de usar o fluxo de cancelamento é evitar endpoints diferentes mas que fazem a mesma função.

**Comment by gui-camargo** [comment]
Conforme conversado em comitê, não vamos efetuar nenhuma alteração nesse sentido.
Será adicionada a documentação uma recomendação de envio do webhook de atualização nos casos em que tiverem discrepancias no pedido, mas mesmo assim o pedido for confirmado pelo merchant.

Como não tivemos mais comentários, estou fechando a issue.
