### ISSUE TITLE
[HubDelivery] Remover a necessidade de informar o OrderId e EventType durante um Acknowledege

### ISSUE THREAD

**Issue by brayannluiz** [Abrasel-Nacional/opendelivery#52]
Durante o processo de acknowledge de eventos, é esperado um objeto com três propriedades conforme exemplo abaixo:
```
{
"id": "string",
"orderId": "string",
"eventType": "CREATED"
}
```

Porém, vemos que não há a necessidade de se informar o OrderId e o EventType pois essas informações já estão implicitas para o Ordering Application quando mandamos o EventId.

Sugerimos entáo que durante um Acknowledge, seja exigido somente o campo Id (referente ao Id do Evento).

**Comment by gui-camargo** [comment]
Olá @brayannluiz,

Esses campos foram incluídos para seguir o padrão de algumas aplicações que já estão no mercado. Vamos discutir a issue, mas acredito que são informações que não causam nenhuma complexidade no endpoint, e por isso poderiam permanecer.

**Comment by gui-camargo** [comment]
Conforme conversado no comitê, não vamos efetuar a remoção destes campos.
