### ISSUE TITLE
[HubDelivery] Alterar padrão de formato de parâmetro na requisição de cancelamento de pedidos

### ISSUE THREAD

**Issue by brayannluiz** [Abrasel-Nacional/opendelivery#53]
Durante o processo de cancelamento de pedidos, nota-se que alguns campos estão seguindo o padrão de nomenclatura com underlines como separador de palavras. Exemplo:

- out_of_stock_items
- invalid_items

Sugiro que o padrão camelCase seja padronizado para todos os parâmetros usados na documentação.

**Comment by gui-camargo** [comment]
Olá @brayannluiz 

Obrigado pela sugestão. Realmente está incorreto e será necessário corrigir na próxima versão.

**Comment by gui-camargo** [comment]
Alterado os atributos out_of_stock_items e invalid_items do endpoint /orders/{orderId}/requestCancellation para outOfStockItems e invalidItems corrigindo-os para o padrão camelCase utilizado no restante da documentação.

Disponível na versãp rc.7
