### ISSUE TITLE
[HubDelivery] Adicionar suporte ao tipo Indoor

### ISSUE THREAD

**Issue by hubdelivery** [Abrasel-Nacional/opendelivery#54]
Suportar pedidos criados pela mesa / tablet

Ao OrderDetail adicionar o type **INDOOR** e um novo objeto à consulta de pedidos.

Exemplo
![image](https://user-images.githubusercontent.com/91287812/140075316-3deedd3e-c1f4-49bd-abcb-c88c5ffcb982.png)

**Comment by gui-camargo** [comment]
Olá @hubdelivery 

Essa funcionalidade foi discutida durante os grupos de trabalho e ficou decidido deixar em backlog, para implementação na próxima versão.

**Comment by hubdelivery** [comment]
Excelente.
Nós já identificamos alguns parceiros que trabalham com a solução indoor e gostariam de entrar no padrão.
Acredito que seja necessário levarmos novamente para a discussão.

**Comment by gui-camargo** [comment]
@hubdelivery efetuamos a discussão no comitê, e as partes concordaram em deixar para um próximo incremento de versão, já priorizando este tema nos grupos de trabalho de melhorias que serão ainda criados para tratar os temas das próximas versões.
