### ISSUE TITLE
[HubDelivery] Adicionar totalizador do custo de entrega

### ISSUE THREAD

**Issue by hubdelivery** [Abrasel-Nacional/opendelivery#55]
Adicionar totalizador do custo de entrega na seção **total** do detalhe do pedido.

![image](https://user-images.githubusercontent.com/91287812/140168819-9ac12367-713d-4152-a4ae-698d3b37bcd6.png)

**Comment by gui-camargo** [comment]
Olá @hubdelivery,

O total do custo da entrega seria informado no campo otherFees. 

No objeto otherFees (fora do totals) é informado a taxa de entrega especifica.
![image](https://user-images.githubusercontent.com/80956588/140171299-c7fae787-87b9-4f80-9545-0278b0522e4c.png)

**Comment by hubdelivery** [comment]
Olá @gui-camargo , notamos essa informação em otherfees, porém como temos os totalizadores, seria ideal também termos esse dado já totalizado.

É uma sugestão de organização de padronização dos totalizadores

**Comment by gui-camargo** [comment]
Olá @hubdelivery, no comitê discutimos que como já temos uma totalização do otherFees (no objeto totals) e a taxa de entrega já está discriminada no otherFees, não teríamos a necessidade de colocar um totalizador próprio para isso, que irá sempre refletir o mesmo valor que já foi discriminado anteriormente. Na teoria a taxa de entrega é uma só por pedido, então um campo de soma especificamente dessa taxa ficaria redundante, porque não teríamos 2 taxas de entrega para somar.

**Comment by gui-camargo** [comment]
Como não tivemos mais comentários, vamos fechar a issue.
