### ISSUE TITLE
[QueroDelivery] Padronizar o atributo state no objeto de endereço na rota /merchant

### ISSUE THREAD

**Issue by plinioaugusto** [Abrasel-Nacional/opendelivery#56]
Fica a sugestão em padronizar o atributo "state" no objeto de endereço da rota de merchant.

Na documentação temos apenas a regra que o atributo deve ser do tipo "string". Assim, existe a possibilidade de assumir valores tanto por externo, quando abreviados para os estados.

Exemplo: Bahia ou BA.

Portanto, fica a sugestão de incluir na documentação um padrão REGEX para esse atributo (como foi feito com o atributo "country"), para que assim, assumisse valor abreviado ou completo por extenso. Para o padrão abreviado, existem os códigos das subdivisões dos países presentes no padrão ISO 3166-2.

**Comment by gui-camargo** [comment]
Olá @plinioaugusto,

Colocamos a recomendação para utilização do ISO 3166-2, mas não de forma obrigatória.

Está disponível na versão rc.8.
