### ISSUE TITLE
[e-Deploy] - Especificação do App-Id

### ISSUE THREAD

**Issue by eduardoalmeida** [Abrasel-Nacional/opendelivery#57]
Atualmente a especificação do campo **X-App-Id** é "An Unique Identificator of the **Ordering Application**".

Eu havia entendido que esse seria um ID único do "Ordering Application" para todos os "Sofware Services".  Em conversa com a Delivery Center eles entenderam que esse ID seria o identificador do "Ordering Application" para um "Software Service" específíco. Dessa forma haveria um ID para a integração "DeliveryCenter <> e-Deploy" e outro ID diferente para a integração "DeliveryCenter <> Links" por exemplo.

Eu entendi que o ID era único para todas as integrações pois a função dele seria apenas de identificar o client_secret (junto com o X-App-MerchantId) para conferência da assinatura (X-App-Signature). Não vejo vantagens desse ID ser por integração. Seria um parâmetro a mais que teria que ser gerado por integração, agregando complexidade e sem ganhos funcionais ou de segurança. Sendo por integração, ainda existe a dúvida de quem é o responsável por gerar esse número e passar para a outra parte.

Precisamos definir o comportamente esperado do campo e melhorar a documentação para deixar esse comportamento mais explícito.

**Comment by gui-camargo** [comment]
Oi @eduardoalmeida,

A ideia era ser um Id único a ser utilizado para todas as integrações, da maneira que você entendeu mesmo. Podemos discutir no comitê para melhor o entendimento. A ideia é, utilizando o seu mesmo exemplo, que a Delivery Center ter o Id dela, e passar este Id nesse campo, independente com quem está ocorrendo a integração.

**Comment by gui-camargo** [comment]
Está sendo tratada na issue Abrasel-Nacional/docs#82 .
