### ISSUE TITLE
[PedePronto] BasicInfo.address.country do JSON de exemplo é inválido, seguindo a própria especificação

### ISSUE THREAD

**Issue by anderson-otuka-dextra** [Abrasel-Nacional/opendelivery#58]
No JSON de exemplo do Basic Info https://abrasel-nacional.github.io/docs/#section/BasicInfo,
- `country` está preenchido com `"Brazil"`.
![image](https://user-images.githubusercontent.com/16103922/143498470-66b7e700-06e8-4e8a-89e2-b20a6071d1bd.png)
- a especificação pede código ISO 3166-1 alpha-2
![image](https://user-images.githubusercontent.com/16103922/143498448-d6cefa09-d6f3-4e53-aca0-3c2a47d082c0.png)

**Comment by gui-camargo** [comment]
Exemplos corrigidos.

Disponível na versão rc.7
