### ISSUE TITLE
[PedePronto] Campo currency dos JSONs de exemplo não segue ISO 4217

### ISSUE THREAD

**Issue by anderson-otuka-dextra** [Abrasel-Nacional/opendelivery#59]
De acordo com a especificação de currency do Open Delivery, em vários trechos, é esperado:

- `string^[A-Z]{3}$`
The 3-letter ISO 4217 currency code.

Em vários JSONs de exemplo consta o valor "`R$`" na currency, onde deveria ser `BRL`.
![image](https://user-images.githubusercontent.com/16103922/143499278-21d56024-6ab3-4ead-9bd6-5a8fdc44bff3.png)
![image](https://user-images.githubusercontent.com/16103922/143499303-9c5df7be-8c52-40c7-ac87-6c2a6147985a.png)
![image](https://user-images.githubusercontent.com/16103922/143499324-11d1dc0d-b6c3-49cf-8bc0-a433b2c896f2.png)
![image](https://user-images.githubusercontent.com/16103922/143499360-a6940a7e-4d50-4ceb-8e47-20cb01bfc4ea.png)

**Comment by gui-camargo** [comment]
Exemplos corrigidos.

Disponível na versão rc.7
