### ISSUE TITLE
[Americanas Delivery] Entidade preparationTime no endpoint confirm

### ISSUE THREAD

**Issue by alanbarcelos1998** [Abrasel-Nacional/opendelivery#6]
Na Americanas Delivery trabalhamos com o recebimento da entidade preparationTime na payload do endpoint confirm. 
 
 Essa entidade é necessária para nós, pois a mesma é essencial na nossa regra de negócio se tratando da confirmação do pedido.

**Comment by gui-camargo** [comment]
Olá @alanbarcelos1998,

Conforme conversamos no comite, vamos incluir este campo na próxima versão da API.

**Comment by gui-camargo** [comment]
Olá @alanbarcelos1998,

A alteração já está disponível na versão release.

Changelog:

>[POST /v1/orders/{orderId}/confirm](#operation/confirmOrder)
>  - added new optional field `preparationTime` to endpoint .
>  This field is used to indicate the estimated time to prepare the order.

A issue será fechada.
