### ISSUE TITLE
[PedePronto] Latitude e Longitude estão especificados como number e também string

### ISSUE THREAD

**Issue by anderson-otuka-dextra** [Abrasel-Nacional/opendelivery#60]
Em alguns trechos da documentação, os campos de Latitude e Longitude são representados como `string`.
Em outros, como `number`.

Seria consistente adotar um padrão único (preferencialmente numérico com precisão decimal de 5 casas)

Seguem alguns exemplos abaixo:

## 1. number
- Trechos
    - /logistics/availability
        - https://abrasel-nacional.github.io/docs/#tag/logisticPrice/paths/~1logistics~1availability/post
    - BasicInfo
        - https://abrasel-nacional.github.io/docs/#section/BasicInfo
   - Service.serviceArea.geoRadius
        - https://abrasel-nacional.github.io/docs/#section/Service
- Especificação
![image](https://user-images.githubusercontent.com/16103922/143499693-38883d8a-5637-413d-bedf-3c1ad905a2e3.png)
![image](https://user-images.githubusercontent.com/16103922/143499953-0962975f-a9f8-41ed-83ba-0f01bd720f2b.png)

- JSON de exemplo
![image](https://user-images.githubusercontent.com/16103922/143499717-80228443-51fe-4fe4-a78b-f751f01887ec.png)
![image](https://user-images.githubusercontent.com/16103922/143499931-ba238d36-5bb9-47c7-869e-cd1041e91e8e.png)

## 2. string
- Trechos
    - Tracking event webhook (geoLocalization)
        - https://abrasel-nacional.github.io/docs/#operation/newLogisticEvent
    - Especificação
    ![image](https://user-images.githubusercontent.com/16103922/143500109-3bd93a46-5031-4d41-bcb5-c25687841550.png)
    - JSON de exemplo
    - ![image](https://user-images.githubusercontent.com/16103922/143500139-8108a739-36ab-442f-8efa-699956398070.png)

**Comment by gui-camargo** [comment]
Olá @anderson-otuka-dextra ,

Todos os atributos latitude e longitude tiveram seu formato alterado para number com precisão de 5 casas decimais. Objetos afetados:
Address
Polygon
GeoRadius
Order
GeoLocalization

Estará disponível na versão rc.8.
