### ISSUE TITLE
[PedePronto] Campos "image" estão representados como string nos JSONs de exemplo, e não objetos

### ISSUE THREAD

**Issue by anderson-otuka-dextra** [Abrasel-Nacional/opendelivery#61]
Nos exemplos JSON, `image` é representado incorretamente como `string` contendo uma URL.

1. A especificação referencia os campos `image`, `logoImage` e `bannerImage` como objetos contendo os campos `URL` e `CRC-32` (opcional).
2. A especificação define todo campo `image` como "image of the merchant logo", sendo que existem imagens com outros fins, como banner, itens e categorias do cardápio.

# Exemplos
## 1. Basic Info
https://abrasel-nacional.github.io/docs/#section/BasicInfo
- JSON
![image](https://user-images.githubusercontent.com/16103922/143500724-bb286d60-8f34-4c3f-a170-cd928a38d75a.png)
- Especificação
![image](https://user-images.githubusercontent.com/16103922/143500620-26c7acb4-9ab5-46f3-99eb-46239430f635.png)

## 2. Category
https://abrasel-nacional.github.io/docs/#section/Menu/Category
- JSON
![image](https://user-images.githubusercontent.com/16103922/143500673-ef80e578-ba31-46b5-b692-06e4de88b460.png)
- Especificação
![image](https://user-images.githubusercontent.com/16103922/143500781-da7bb662-c57b-4620-8f1e-3b05a1a0d27c.png)

## 3. Menu
https://abrasel-nacional.github.io/docs/#section/Menu/Item
- JSON
![image](https://user-images.githubusercontent.com/16103922/143500690-96159c1f-7cc1-4c07-adad-c62e549b6b7d.png)
- Especificação
![image](https://user-images.githubusercontent.com/16103922/143500839-ac7682c3-1629-46d1-b6a2-b71d757379c2.png)

**Comment by gui-camargo** [comment]
Exemplos corrigidos.

Disponível na versão rc.7
