### ISSUE TITLE
[Quiq] Tornar opcional o campo "metadata" e "metadata.clientId" no evento CONFIRMED

### ISSUE THREAD

**Issue by alencardc** [Abrasel-Nacional/opendelivery#62]
Notamos que na especificação dos eventos do polling e do webhook o campo `clientId` dentro de `metadata` é opcional para todos os eventos do fluxo de cancelamento (`ORDER_CANCELLATION_REQUESTED`, `CANCELLATION_REQUESTED`, `CANCELLATION_REQUEST_DENIED` e `CANCELLED`), porém no evento de `CONFIRMED` o objeto `metadata` possui apenas o campo `clientId` e ambos são obrigatórios.

Dado que no fluxo de cancelamento esse campo (`clientId`) é opcional e a especificação define ele como: *The ID of the client system that generated the action that resulted in this event **(to be used with application with multiple stations)***, então poderíamos defini-lo como opcional para o evento de `CONFIRMED` também e, assim, padronizar a definição do campo em todos eventos em que esse campo aparece.

Atual estrutura do evento `CONFIRMED`:

![OpenDelivery-CONFIRMED-required](https://user-images.githubusercontent.com/16635772/150338318-d4d15f69-a687-4389-872b-84702c9bceb4.PNG)

Sugestão de nova estrutura do evento `CONFIRMED`:

![OpenDelivery-CONFIRMED-optional](https://user-images.githubusercontent.com/16635772/150338384-79e70ea6-5243-4539-9461-ea06ff57a748.PNG)

**Comment by gui-camargo** [comment]
Olá @AlencarDC,

A obrigatoriedade do campo clientId do metadata do objeto Event do pedido para os eventType = CONFIRMED foi retirada conforme sugerido.

Já disponível na versão rc-10.
