### ISSUE TITLE
[POS CONTROLE] Resposta do body do polling deveria ser um array

### ISSUE THREAD

**Issue by fabiosoliveira** [Abrasel-Nacional/opendelivery#63]
No exemplo do body GET /events:polling a resposta está como um objeto simples:
`{
        "eventId": "string",
        "eventType": "CREATED",
        "orderId": "string",
        "orderURL": "http://example.com",
        "createdAt": "2019-08-24T14:15:22Z"
 }`

quando deveria estar dentro de um array:

`[
    {
            "eventId": "string",
            "eventType": "CREATED",
            "orderId": "string",
            "orderURL": "http://example.com",
            "createdAt": "2019-08-24T14:15:22Z"
      }
 ]`

**Comment by gui-camargo** [comment]
Olá @fabiosoliveira,

A correção foi efetuada, e já está disponível na versão rc-10.
