### ISSUE TITLE
[Hub Delivery] - Documentação Webhook Pedidos (Headers)

### ISSUE THREAD

**Issue by hubdelivery** [Abrasel-Nacional/opendelivery#64]
Notamos que o parâmetro **X-App-MerchantId** está definido como UUID, porém pela especificação é a junção do CNJP + UUID e dessa maneira o parâmetro deveria ser somente string.

![image](https://user-images.githubusercontent.com/91287812/152259991-a5ad9bb7-fbf3-4da5-afa2-633f9fb534b7.png)

**Comment by gui-camargo** [comment]
Olá @hubdelivery,

O format UUID foi retirado dos campos de Id do Merchant, conforme sugerido.

Já disponível na versão rc-10.
