### ISSUE TITLE
[QUIQ] Formato do query param "eventType" no endpoint de polling

### ISSUE THREAD

**Issue by alencardc** [Abrasel-Nacional/opendelivery#65]
No endpoint de polling há o campo `eventType` que é passado como query param.
Esse campo é definido como um array de tipos de eventos que deverão ser retornados pelo endpoint de polling, porém não é definido qual o formato desse array. 

Arrays costumam ser passados como query param de diversas formas, sendo as mais comuns exemplificadas abaixo.
- `?eventType=CREATED&eventType=CONFIRMED&eventType=DISPATCHED`
- `?eventType[]=CREATED&eventType[]=CONFIRMED&eventType[]=DISPATCHED`
- `?eventType[]=CREATED,CONFIRMED,DISPATCHED`
- `?eventType=CREATED,CONFIRMED,DISPATCHED`

Dado que existem diferentes formatos comumente utilizados e que diferentes tecnologias costumam ter seu próprio formato padrão, acho válido padronizarmos o formato que deverá ser utilizado para esse tipo de campo e enfatizá-lo na documentação.

Qual a opinião de vocês a respeito da padronização do formato desse campo?

**Comment by gui-camargo** [comment]
Olá @AlencarDC,

Pelas conversas que tive com algumas empresas, a solução que está sendo mais aderida é a:
`?eventType=CREATED&eventType=CONFIRMED&eventType=DISPATCHED`
mas concordo que precisamos definir o padrão.
Vamos levar ao próximo comite para discussão e posteriormente incluir nos guidelines da documentação.

**Comment by gui-camargo** [comment]
Olá @AlencarDC ,

Conforme discutido no comitê técnico, foi adotada o seguinte padrão para os requests:

- For `QUERY` parameters:
    ```
    ?param=X&param=Y&param=Z
    ```

- For `HEADER` parameters:
```
    param: X
    param: Y
    param: Z
```
A orientação foi incluída na seção de [Guidelines](https://abrasel-nacional.github.io/docs/#section/General-Guidelines) da documentação.
