### ISSUE TITLE
[PedePronto] Dúvida sobre integração para rede de restaurantes

### ISSUE THREAD

**Issue by varronche** [Abrasel-Nacional/opendelivery#66]
Boa tarde @gui-camargo 
Temos uma dúvida sobre a integração de uma rede de restaurantes. Hoje a documentação refere-se a uma única loja. 
Existe a pretensão de inclusão de contrato guiado a grandes redes (merchantGroups) para atualizações de dados de suas lojas (como por exemplo horário de funcionamento e atualização de cardápio)?

**Comment by gui-camargo** [comment]
Olá @varronche, conforme já conversamos, hoje ficaria como responsabilidade do Software Service controlar os grupos de Merchant e atualizações massivas para vários merchants. Neste momento o padrão somente trata as informações de 1 merchant por vez.
De qualquer maneira vemos levar este assunto para o backlog do projeto.
