### ISSUE TITLE
[Bdoo] Endpoint POST /logistics/delivery

### ISSUE THREAD

**Issue by douglasapolinario** [Abrasel-Nacional/opendelivery#67]
Gostaria de saber qual valor vem no campo pickupLimit e deliveryLimit do limitTimes, seria quilometro ou metros?

**Comment by gui-camargo** [comment]
Olá @douglasapolinario, obrigado pela issue. Conforme já conversado em comitê os campos se referem aos limites de tempo, e deverão ser preenchidos em minutos. Efetuei um ajuste na descrição dos campos para deixar mais claro a função dos mesmos.

Estará disponível na versão 1.1.0-rc.3.

**Comment by gui-camargo** [comment]
Olá @douglasapolinario, já está disponível na documentação a melhoria nas descrições dos campos. Irei fechar a issue.
