### ISSUE TITLE
[Hub Delivery] - Ajuste de exemplos

### ISSUE THREAD

**Issue by hubdelivery** [Abrasel-Nacional/opendelivery#68]
Notamos algumas divergências nos exemplos do endpoint de obtenção de dados do merchant.

Acreditamos importante deixar os exemplos e as definições em conformidade.

Segue exemplo de inconformidade nos items.

![image](https://user-images.githubusercontent.com/91287812/149189868-766ffd5a-2164-4b59-969e-554d4b932fa3.png)

![image](https://user-images.githubusercontent.com/91287812/149189934-04aee2bf-1fe5-4b87-902e-6f3c1a7fd37c.png)

**Comment by gui-camargo** [comment]
Oi @hubdelivery, revisei os exemplos dos itens e eles estão de acordo a definição. O único ponto é que não está preenchido os dados não obrigatórios de alguns dos exemplos. Você poderia apontar se existe alguma outra inconsistência por favor, para que eu verifique e corrija.

**Comment by gui-camargo** [comment]
Como não tivemos mais comentários, estou fechando a issue.
