### ISSUE TITLE
[e-Deploy] URL /merchant para várias lojas de uma mesma integração

### ISSUE THREAD

**Issue by eduardoalmeida** [Abrasel-Nacional/opendelivery#69]
Para obter o cardápio temos apenas a URL /merchant e em nenhum lugar é especificado de qual loja se deseja obter o cardápio. Se houver mais de uma loja para integração, não ficou claro como será obtido o cardápio de cada loja.

Algumas possibilidades possíveis:
1 - Cadastro de URL base por loja
2 - Escolha de lojas ficar pela api-key
3 - Alterar especficação para determinar a loja para qual o cardápio está sendo solicitado

A solução 1 seria a mais simples mas necessitaria que o cliente obtivesse uma URL para cada loja do "Software Service" e fizesse o cadastro de cada uma delas no "Ordering Application"

A solução 2 tem a mesma deficiência fazerndo que o cadastro de API-KEY ficasse por loja. Ao meu ver é a que faz menos sentido pois a api-key é uma autenticação o "Ordering Application" no "Sofware Service" não se relacionando com loja.

A solução 3 seria alterar a URL para algo do tipo "{merchantId}/merchant" e isso precisaria que o parâmetro "merchantId" fosse fornecido pelo "Software Service" e cadastrado no "Ordering Application" ou o contrário.

**Comment by gui-camargo** [comment]
Está sendo tratada na issue Abrasel-Nacional/docs#82 .
