### ISSUE TITLE
Ecletica Food - Vínculo do detalhamento de bandeiras PDV x MKTPlaces

### ISSUE THREAD

**Issue by EcleticaDev** [Abrasel-Nacional/opendelivery#7]
Pessoal, bom dia. Falo em nome da equipe de desenvolvimento da Ecletica Tecnologia, onde estamos adotando o padrão Open Delivery para troca de informações com nosso parceiros marketplaces e midlewares. Gostaríamos de saber se será implementado em documentações futuras, uma tag similar ao que o IFood já tem hoje, chamada Brand, onde nela chegaria para nós o detalhe da bandeira de cartão, voucher ou ticket, como VISA_CREDITO, MASTER_DEBITO, SODEXO , etc. Hoje no OD exite apenas o method, que retorna o meio, por exemplo "CASH", "CREDIT", "DEBIT", "OTHER", fazendo com que do nosso lado  software service se torne difícil a vinculação com os detalhes de bandeira cadastrados pelos nossos clientes lojistas. O Guilherme havia sugerido usar a tag methodInfo para estes casos, mas não se sabe o que cada marketplace enviará nessa tag, e também, se ela será de fato enviada pois é opcional e a recomendação de vocês é apenas no caso de informar "OTHER" na tag method. Isso é muito importante para nós, pois é um problema crônico que temos com vários marketplaces, gerando transtorno sempre para o lojista, que fica sem saber o detalhe correto da venda que chegou via determinada plataforma. O vínculo para nós é obrigatório, pois internamente no sistema, fornecemos uma série de informações de conciliação, DRE, estatísticas, recebimentos de títulos a vencer e a pagar.

**Comment by gui-camargo** [comment]
Olá @EcleticaDev,

Conforme conversamos no comite, vamos incluir o campo brand, na entidade de payments do pedido na próxima versão da API.

**Comment by EcleticaDev** [comment]
Muito obrigado pelo apoio Guilherme.

 

 

 

Atenciosamente,

 

Francisco Moura



 

De: Guilherme Camargo ***@***.***> 
Enviada em: quarta-feira, 14 de setembro de 2022 13:58
Para: Abrasel-Nacional/docs ***@***.***>
Cc: Francisco Moura ***@***.***>; Mention ***@***.***>
Assunto: Re: [Abrasel-Nacional/docs] Ecletica Food - Vínculo do detalhamento de bandeiras PDV x MKTPlaces (Issue #7)

 

Olá @EcleticaDev <https://github.com/EcleticaDev> ,

Conforme conversamos no comite, vamos incluir o campo brand, na entidade de payments do pedido na próxima versão da API.

**Comment by gui-camargo** [comment]
Olá @EcleticaDev 

A alteração já está disponível na versão release.

Changelog:

>[GET /v1/orders/{orderId}](#operation/ordersDetails)
>- added new optional field `brand` to the `payments>methods` entity.
> This field is intended to indicate the brand of the card (for cases where the chosen payment method has a brand).

A issue será fechada.
