### ISSUE TITLE
[Carga24h Delivery] Valor da Taxa de Entrega

### ISSUE THREAD

**Issue by RicardoSoeltl** [Abrasel-Nacional/opendelivery#70]
Após a requisição de uma nova ordem, desde que confirmada, o Valor da Taxa de Entrega, do serviço de Logística para o SW do Estabelecimento. Dado não obrigatório.

**Comment by gui-camargo** [comment]
Olá @RicardoSoeltl .

Os campos de preço estavam incorretos nas APIs de Logística.
Foi corrigido os campos `deliveryPrice` que estavam referenciando um schema incorreto. 
Endpoints afetados:
Delivery Tracking
Delivery Availability and Pricing

Já disponível na versão rc.2 .
