### ISSUE TITLE
[e-Deploy] Retorno do Polling quando não há eventos

### ISSUE THREAD

**Issue by eduardoalmeida** [Abrasel-Nacional/opendelivery#71]
Na descrição do polling está falando:

Query new order events
In order to receive new order events, the merchant Software Service must make requests on the polling endpoint regularly at a certain time interval, determined by the 'Ordering Application'. Whenever there is a new event the response will send the response code 200 with the list of events. If there are no new events, the response will send the response code 204.

Quando não há eventos deve-se retornar um 204.

Mas, na especificação do método de polling não existe o 204 como um response válido:

https://abrasel-nacional.github.io/docs/#operation/pollingEvents

**Comment by gui-camargo** [comment]
Olá @eduardoalmeida.

Foi incluído o response para o HTTP 204 no endpoint `GET /events:pooling`.

Já disponível na versão rc.9 .
