### ISSUE TITLE
[PedePronto] JSON de exemplo do /merchant apresenta contactPhones como array e não objeto

### ISSUE THREAD

**Issue by anderson-otuka-dextra** [Abrasel-Nacional/opendelivery#75]
Na especificação, `contactPhones` é um objeto.
Em um dos exemplos, `contactPhones` está representado como um array de objetos.

- Especificação - https://abrasel-nacional.github.io/docs/#section/BasicInfo
![image](https://user-images.githubusercontent.com/16103922/143502428-b58226d4-af73-47fa-a6cb-cd1e2ceebd00.png)
- JSON do BasicInfo (correto) - https://abrasel-nacional.github.io/docs/#section/BasicInfo
![image](https://user-images.githubusercontent.com/16103922/143502397-fdf70006-d06e-43b4-8890-2aa87ce3c027.png)
- JSON do /merchant (inconsistente) - https://abrasel-nacional.github.io/docs/#operation/getMerchant
![image](https://user-images.githubusercontent.com/16103922/143502359-8f9b89d5-7be7-4367-a73c-e7ac97216fe0.png)

**Comment by gui-camargo** [comment]
Exemplos corrigidos.

Disponível na versão rc.7
