### ISSUE TITLE
[PedePronto] JSON de exemplo do /merchant tem services[] inconsistente com o Service

### ISSUE THREAD

**Issue by anderson-otuka-dextra** [Abrasel-Nacional/opendelivery#76]
Inconsistência encontrada em https://abrasel-nacional.github.io/docs/#operation/getMerchant
- Especificação (navegar até services[].serviceArea)
![image](https://user-images.githubusercontent.com/16103922/143502767-57d0bab7-78c3-460a-b100-8a5efe752fba.png)
- JSON (inconsistente)
![image](https://user-images.githubusercontent.com/16103922/143502710-b66c0373-3b87-4c96-89c0-9cf3b382236f.png)

Existe um exemplo correto no Service: https://abrasel-nacional.github.io/docs/#section/Service
- Especificação
![image](https://user-images.githubusercontent.com/16103922/143503106-f4c575a9-8395-4cad-9a51-e730894f01c4.png)
- JSON (correto)
![image](https://user-images.githubusercontent.com/16103922/143502854-604d841d-7219-4c7f-8c7d-13d3c7fa57b3.png)

**Comment by gui-camargo** [comment]
Exemplos corrigidos.

Disponível na versão rc.7
