### ISSUE TITLE
[PedePronto] Inconsistência JSON /merchant: weekHours é um array com objetos inválidos

### ISSUE THREAD

**Issue by anderson-otuka-dextra** [Abrasel-Nacional/opendelivery#80]
No JSON de exemplo do /merchant, `services[0].serviceHours.weekHours` é um array com 2 objetos, um com o campo `dayOfWeek` e outro com `timePeriods`.

Na especificação, ambos os campos `dayOfWeek` e `timePeriods` são obrigatórios para todos os objetos do array `weekHours`.

Link: https://abrasel-nacional.github.io/docs/#operation/getMerchant

- Especificação
![image](https://user-images.githubusercontent.com/16103922/143503548-64cc6120-d43e-4f24-acfd-5a9394e98d7c.png)
- JSON de exemplo (inconsistente, errado)
![image](https://user-images.githubusercontent.com/16103922/143503403-d6650682-0cab-4cd4-8c4e-dbaaf8e4316e.png)
- Outro JSON de exemplo correto (em https://abrasel-nacional.github.io/docs/#section/Service)
![image](https://user-images.githubusercontent.com/16103922/143503595-e99a18d9-11e1-4a30-b711-91a944d1171e.png)

**Comment by gui-camargo** [comment]
Exemplos corrigidos.

Disponível na versão rc.7
