### ISSUE TITLE
[DeliveryVIP] Campo "reference" em deliveryAddress

### ISSUE THREAD

**Issue by juliano-sfhera** [Abrasel-Nacional/opendelivery#81]
Não encontramos o campo "reference" em deliveryAddress.

Em outras apis como ifood existe este campo e consideramos de extrema relevância, pois ele tem papel diferente do complement.

Exemplo iFood:

![image](https://user-images.githubusercontent.com/11891292/145580938-6e795486-ffc5-4ff4-8e82-45922aaacda9.png)

Um exemplo disto seria:
 complemento: APTO 402/BLOCO B
 referencia: proximo ao estabelecimento xyz.

Att.

**Comment by gui-camargo** [comment]
Olá @sfhera.

O campo de `reference` foi incluído nos objetos de endereço.

Já disponível na versão rc-8.
