### ISSUE TITLE
[e-Deploy] Descrição e código de cancelamento no requestOrderCancellation

### ISSUE THREAD

**Issue by eduardoalmeida** [Abrasel-Nacional/opendelivery#83]
A descrição do método requestCancellation (https://abrasel-nacional.github.io/docs/#operation/requestCancellation) está como:

"Request for order cancellation has been accepted."

Nos possíveis valores do campo code do request o valor "INTERNAL_DIFFICULTIES_OF THE RESTAURANT" está sem os dois últimos "_"

**Comment by gui-camargo** [comment]
Olá @eduardoalmeida.

O texto descritivo foi removido, e a opção corrigida para `INTERNAL_DIFFICULTIES_OF_THE_RESTAURANT`.

Já disponível na versão rc.9 .
