### ISSUE TITLE
[Hub Delivery] - Remoção do header "x-polling-merchants"

### ISSUE THREAD

**Issue by hubdelivery** [Abrasel-Nacional/opendelivery#84]
Sugerimos que o header **x-polling-merchants** seja removido, visto que o contexto de autenticação é individual por Merchant.

![image](https://user-images.githubusercontent.com/91287812/148995971-ad705a66-aaac-4534-8179-edbb338cb7a0.png)

**Comment by danieldocki** [comment]
No DeliveryVip implementamos que uma aplicação pode consumir mais de um merchant, então no request das orders é possível ele pegar todas as orders ou de alguns merchants.

**Comment by gui-camargo** [comment]
Olá @hubdelivery e @danieldocki, conforme conversado no comitê do dia 13/01/2022, como descrito pelo @hubdelivery a autenticação é feita individual por merchant o que deixa o campo sem função neste primeiro momento, mas foi decidido manter o campo, para já deixar contemplado para versões futuras a possibilidade de obter de vários merchants. Ainda é possível utilizar este campo para obter vários merchant, caso haja um combinado entre o Software Service e a Ordering Application, mas isso seria feito fora do padrão, pelo menos para a versão 1.0.0 .
