### ISSUE TITLE
Data inválida no json de exemplo para o atributo `holidayHours.date`

### ISSUE THREAD

**Issue by danielgoncalves** [Abrasel-Nacional/opendelivery#86]
Conforme a imagem abaixo, a data de exemplo para o atributo `Service.serviceHours.holidayHours[0].date` está fora do padrão documentado. Deveria ser `2021-04-07`, assumindo que o exemplo está no formato dia/mês/ano,

![image](https://user-images.githubusercontent.com/737884/153268225-b1857e30-fb9b-42c7-b815-bb1e8d2a08f0.png)

**Comment by gui-camargo** [comment]
Olá @danielgoncalves,

Vou efetuar a correção. Obrigado.

**Comment by gui-camargo** [comment]
Olá @danielgoncalves,

A correção já foi efetuada na documentação.
