### ISSUE TITLE
Order Details -> preparationStartDateTime

### ISSUE THREAD

**Issue by danieldocki** [Abrasel-Nacional/opendelivery#87]
O field `preparationStartDateTime` em `Order Details` está como requerido, mas só teremos o tempo do começo do preparo somente quando o pedido for aceito, possibilidade de deixar requerido somente depois de aceito esse field?

**Comment by gui-camargo** [comment]
Olá @danieldocki,

Conforme discutido no comitê, a ideia do campo é para que a Ordering Application posso já sugerir um inicio da preparação. considerando fatores de logisticas e tempos passados.

Alterei o texto para:
>Suggestion for the preparation start time after Order creation. This can be used by the Ordering Application to inform the merchant to delay the start of the preparation for any reason. Default is the same time as the order creation time.

Vamos manter a obrigatoriedade do campo, sendo que por padrão deve ser enviado a mesma hora de criação do pedido.

Já disponível na versão rc11.
