### ISSUE TITLE
[QUIQ] Atualização de Entidade de Item

### ISSUE THREAD

**Issue by Gregcjni** [Abrasel-Nacional/opendelivery#88]
Olá

Me chamo Gregory, faço parte da empresa Quiq e atuo aqui como Lider Técnico. Me passaram teu contato pra que eu pudesse tirar dúvidas sobre o protocolo Open Delivery, por isso estou montando este email pra esclarecer a dúvida que segue abaixo:

Estamos trabalhando na disponibilização de cardápios na nossa API que irá trabalhar com este protocolo e queria entender como posso trafegar detalhes do escopo de itens de um cardápio.

A dúvida se dá no seguinte contexto, entendemos que para fazermos a publicação de atualizações de cardápio utilizamos a atualização do Merchant, podemos sinalizar via WebHook que há atualização nos nossos dados, e deixar com que o "client" busque todas as informações através de um Get para realizar a alteração.

Mas no nosso caso, também gostaríamos de explorar a atualização através de um escopo mais detalhado, como por exemplo atualizar a categoria ou um item, trafegando um "contrato detalhado" (através do entityType e do updateObjects)

![image](https://user-images.githubusercontent.com/11841518/154349216-5f9efcd6-d808-4e14-bb56-783cda02c1c9.png)

Porém, dentro das entidades listadas, não há a opção de trafegar apenas um Item, embora esse esteja no mesmo nível de "escopo" das outras entidades permitidas no contrato do merchant.

![image](https://user-images.githubusercontent.com/11841518/154349244-8b263952-002e-44d7-99f8-908e70d2ef5b.png)

![image](https://user-images.githubusercontent.com/11841518/154349285-b3c92626-f121-4079-b0ee-52f25832a356.png)

Com isso, gostaria de entender com vocês se há outra maneira de trafegar  atualização de detalhamentos específicos de item que não nos atentamos ou se há a possibilidade de incluirmos o detalhamento de itens na lista de entidades a serem atualizadas assim como as outras na documentação do protocolo.

Desde já agradeço pela atenção!

Links de referência:
https://abrasel-nacional.github.io/docs/#tag/merchantEndpoints
https://abrasel-nacional.github.io/docs/#tag/merchantUpdate

**Comment by gui-camargo** [comment]
Olá @Gregcjni ,

Conforme discutido no comite, a opção `ITEM` foi adicionada no /merchantUpdate.

Já disponível na versão rc11.
