### ISSUE TITLE
[PedePronto] Health Check

### ISSUE THREAD

**Issue by varronche** [Abrasel-Nacional/opendelivery#89]
@gui-camargo Bom dia!
Estou com dúvida sobre o health check que deveremos prover ao merchant (/merchantStatus). 
Gostaria de entender se temos que prover a informação de que estamos conseguindo apenas ler do /merchant ou precisamos manipular os dados do /merchant e ao final de toda a atualização deveremos prover esse status?

**Comment by gui-camargo** [comment]
Olá @varronche,

A idéia de criação do endpoint foi para o merchant saber se o cardápio dele está sendo lido corretamente ou se houve algum problema. Então seria a segunda opção da sua pergunta, ou seja, se vocês conseguiram processar e importar as informações para o sistema de vocês, então vocês informam o `SUCCESS`. Se por algum motivo vocês não conseguiram importar aí sim seria o `FAIL` (isso poderia incluir tanto dados incorretos no json, como problemas de comunicação).

**Comment by varronche** [comment]
@gui-camargo perfeito!
Só queria tirar mais uma duvida sobre o assunto: se o merchant chamar o /merchantStatus antes do sistema concluir todas as atualizações, cabe um status adicional de "PROCESSING"?

**Comment by gui-camargo** [comment]
Olá @varronche, podemos discutir esse ponto no próximo comitê sim, na teoria não vejo nenhum problema em adicionar.

**Comment by gui-camargo** [comment]
Olá @varronche,

O status `PROCESSING` foi adicionado ao endpoint.

Já disponível na versão 1.0.0-rc.12 .
