### ISSUE TITLE
Status de cancelamento do pedido

### ISSUE THREAD

**Issue by samuel-silva-dc** [Abrasel-Nacional/opendelivery#9]
A documentação da Open Delivery possui vários eventTypes para o pedido: CREATED, CONFIRMED, DISPATCHED, READY_FOR_PICKUP, PICKUP_AREA_ASSIGNED, CONCLUDED, CANCELLATION_REQUESTED, CANCELLATION_REQUEST_DENIED, CANCELLED, ORDER_CANCELLATION_REQUEST; com o pedido podendo ter somente um status por vez.
Sendo assim, um o pedido com status corrente DISPATCHED, por exemplo, recebe uma solicitação de cancelamento do PDV(CANCELLATION_REQUESTED), alterando seu status atual.
Em seguida, a solicitação é recusada(CANCELLATION_REQUEST_DENIED), alterando seu status novamente. Como o cancelamento não aconteceu, o pedido deve voltar para o status DISPATCHED, último status antes da solicitação de cancelamento, e seguir o fluxo até ser concluído(CONCLUDED). Em que momento a alteração de status CANCELLATION_REQUEST_DENIED para DISPATCHED deve acontecer? Existe alguma orientação para isso?

**Comment by gui-camargo** [comment]
Conforme discutido no comitê do dia 12/08/2021, o padrão do Open Delivery trabalha com o envio e recebimento de eventos do pedido, ficando as atualizações de status do pedido por responsabilidade dos sistemas que estão controlando este pedido. Nenhuma alteração foi feita na documentação.
