### ISSUE TITLE
Atributos "preparationStartDateTime" e "takeoutDateTime" 

### ISSUE THREAD

**Issue by symonlopes** [Abrasel-Nacional/opendelivery#90]
Os atributos "preparationStartDateTime" e "takeoutDateTime" não seriam setados em eventos em um momento posterior à criação do pedido? Aparentemente não temos como possuir essas informações no momento dessa criação.

**Comment by gui-camargo** [comment]
Olá @symonlopes,

A ideia do `preparationStartDateTime` é para ser utilizado caso a ordering application queira adiar o inicio da preparação por qualquer motivo, ela poderia enviar este campo como sugestão para o merchant.
Temos uma issue (#75) tratando deste ponto, mas de qualquer maneira, eu deixei a descrição do campo mais clara.

O `takeoutDateTime` deveria ser enviado com o mesmo tempo que foi mostrado para o consumidor na finalização do pedido na Ordering Application.

De qualquer maneira, se vocês não tem esses tempos antes da confirmação do pedido, podem enviar o mesmo date-time da criação do pedido.

**Comment by gui-camargo** [comment]
Finalizando a issue, por não ter outros comentários.
