### ISSUE TITLE
[Hub Delivery] - Logistica - Padronizar o campo neighborhood / district 

### ISSUE THREAD

**Issue by hubdelivery** [Abrasel-Nacional/opendelivery#91]
Notamos que no detalhe do pedido os campos de endereço tem a nomenclatura diferente daa integração logística (request new delivery).

Ex.: StreetNumber, StreetName, Neighborhood.

Recomendamos padronizar o campos para não gerar confusão de interpretação / implementação.

**Comment by gui-camargo** [comment]
Olá @hubdelivery,

Vou verificar esses pontos e leva-los para discutir no comite, pára verificarmos possiveis correções.

Obrigado pela issue.

**Comment by gui-camargo** [comment]
Olá @hubdelivery,  

Conversamos hoje no comite, e o grupo realmente entendeu como necessário a padronização destes campos.
Como o único lugar em que estes campos estão fora do padrão é na API **`GET /orders/{orderId}`**  e esta API é bem sensível pois vários players já implementaram, vamos esperar uma semana para atualizar a documentação, para que as empresas fiquem cientes da alteração:

Alteração que será efetuada:

Endpoint: **GET /orders/{orderId}**
propriedade: **delivery**

**DE:**

delivery": {
"deliveredBy": "MERCHANT",
"deliveryAddress": {
...
**"neighborhood": "Moema",
"streetName": "Plaza Avenue",
"streetNumber": "100",**
...
},
"estimatedDeliveryDateTime": "2019-08-24T14:15:22Z",
"deliveryDateTime": "2019-08-24T14:15:22Z"
},

**PARA:**

delivery": {
"deliveredBy": "MERCHANT",
"deliveryAddress": {
...
**"district": "Moema",
"street": "Plaza Avenue",
"number": "100",**
...
},
"estimatedDeliveryDateTime": "2019-08-24T14:15:22Z",
"deliveryDateTime": "2019-08-24T14:15:22Z"
},

**Comment by gui-camargo** [comment]
A atualização dos campos foi efetuada;

Já disponível na versão rc.13
