### ISSUE TITLE
Integração aplicativo de pedidos com Software de Serviço

### ISSUE THREAD

**Issue by JulioAugustoS** [Abrasel-Nacional/opendelivery#92]
Como no meu caso, vou fazer integração com os Softwares de Serviços (ERP, PDV etc), quais dados adicionais eu preciso estruturar no meu banco de dados para que essa comunicação com o Software que o restaurante utiliza seja realizada, hoje eu armazeno o cadastro dos restaurantes que aderiram ao meu serviço, nesse caso eu precisarei alterar esse cadastro para salvar algum identificador do software utilizado pelo restaurante, certo?

**Comment by gui-camargo** [comment]
Olá @JulioAugustoS,

Recomendo você ler as sessões [How to Start](https://abrasel-nacional.github.io/docs/#section/How-to-Start-(Setup-Guide)) e a [Estrutura do Merchant](https://abrasel-nacional.github.io/docs/#tag/merchantStructure) para verificar quais informações dos restaurantes são trafegadas no padrão.

Se ainda assim tiver mais duvidas, pode utilizar esta propria issue,

**Comment by gui-camargo** [comment]
Finalizando a issue. Caso necessário pode reabri-la com novas dúvidas.
