### ISSUE TITLE
[BDOO] Request New Delivery sem o nome do Cliente

### ISSUE THREAD

**Issue by eversonbdoo** [Abrasel-Nacional/opendelivery#93]
O request New Delivery não possui nenhum campo de identificação do nome do cliente que receberá o delivery

**Comment by gui-camargo** [comment]
Olá @eversonbdoo,

Foi adicionado o campo `customerName` no endpoint [POST /logistics/delivery](https://abrasel-nacional.github.io/docs/#operation/logisticsNewDelivery).

Já disponível na versão 1.1.0-rc.6 .
