### ISSUE TITLE
[Inter] Dúvidas sobre endpoint de eventos

### ISSUE THREAD

**Issue by cesarcorreiainter** [Abrasel-Nacional/opendelivery#94]
Pessoal, estamos com algumas dúvidas aqui: 

1) se o merchant tem o webhook implementado para notificação de novos pedidos (/orderUpdate) teremos que registrar os eventos dos novos pedidos no mecanismo do pooling como forma de redundância?
2) Chegou-se a ter algum acordo em relação a quanto tempo um evento ficará pendente na fila para pooling?

**Comment by gui-camargo** [comment]
Olá @cesarcorreiainter, seguem respostas. 

1 - Colocamos as duas formas de se trabalhar no padrão para atender o máximo de sistemas possíveis. O ideal é que vocês como marketplace disponibilizem as duas maneiras para os software, e combine com cada um, como vocês preferem se comunicar. Se for pra implantar apenas um, sugerimos o polling pois ele consegue atender também softwares menores e conectados e rede locais.

2 - O tempo do evento do polling fica a cargo de cada marketplace definir. Cada um pode adotar o tempo que melhor atenda. Somente é necessário informar os softwares desse tempo (através de alguma politica, ou guidelines especificos do sistema de vocês).

O que temos na documentação é apenas a recomendação para seguir os tempos determinados pelo marketplace.

```
It is important that the Software Service performs the requests within the timeframe determined by the Ordering Application, as blocking and penalties may occur depending on the application's rules.

Availability of new events in polling:

The Ordering Application may have specific rules about the maximum time new events are available in polling before they are removed.

Always check with the Ordering Application what the rules are for using the polling service.
```

**Comment by cesarcorreiainter** [comment]
Ok. Guilherme. 
Vamos implementar ambos e criar um ttl de 24h para a fila de eventos no pooling, a principio.
