### ISSUE TITLE
[e-Deploy] - Adicionar campo status nas entidades ItemOffer e Option

### ISSUE THREAD

**Issue by eduardoalmeida** [Abrasel-Nacional/opendelivery#95]
Hoje não é possível tirar um produto de venda por indisponibilidade (exemplo algum ingrediente terminou na loja e um produto precisa ser removido). A ideia seria adicionar o campo "status" nas entidades ItemOffer e Option. Dessa forma seria possível atualizar o cardápio apenas trocando o "status" dessa entidades caso se queira remover um produto.
Dessa forma também seria possível usar o endpoint de merchant update para informar apenas essa atualização (sem precisar forçar o market place a consumir todo o cardápio)

**Comment by gui-camargo** [comment]
Olá @eduardoalmeida,

Muito obrigado pela sugestão. Vamos leva-la para conversar no comite.

Apenas para lembrar, como já fizemos o lançamento da versão 1.0.0 de cardápios e pedidos, as próximas atualizações irão entrar num cronograma de releases, a ser ainda divulgado.

**Comment by gui-camargo** [comment]
Solicitação será incluída na próxima versão.

**Comment by gui-camargo** [comment]
Olá @eduardoalmeida,

Os campos foram adicionados na versão 1.0.1 da API.
