### ISSUE TITLE
[QUIQ] Remoção da Obrigatoriedade de campos de Descrição em entidades de Cardápio

### ISSUE THREAD

**Issue by Gregcjni** [Abrasel-Nacional/opendelivery#96]
Olá,

Me chamo Gregory e faço parte do setor de engenharia da empresa Quiq. 

Estou abrindo esta Issue para questionarmos a obrigatoriedade dos campos Description e Disclaimer na entidade Menu, nos "Merchant Endpoints" como segue-se na imagem abaixo.

![image](https://user-images.githubusercontent.com/11841518/163866661-d45fc925-768d-4e4d-bea2-205c30e98d8e.png)

Acreditamos que em algumas vezes realmente há a necessidade de uma descrição para um cardápio, porém há vezes em que já subentende-se o objetivo do cardápio sem que seja necessária uma descrição, como por exemplo "Almoço";

Além disso, temos também o campo descrição como obrigatório na entidade "Categories", onde em nossa percepção temos o mesmo problema: Há vezes em que se faz necessária uma descrição, mas outras vezes o título da categoria já é clara o suficiente, como "Yakisobas", por exemplo.

![image](https://user-images.githubusercontent.com/11841518/163867335-db84298d-f52c-4931-bd00-6550e2c9f5cd.png)

Há o mesmo cenário também no campo de descrição da entidade "Option Groups", onde muitas vezes um grupo de opcionais já tem um nome que torna clara a informação, como "Bebida" dentro de um item.

![image](https://user-images.githubusercontent.com/11841518/163867691-d9e856da-adf4-4e27-9459-a5c6ca593d07.png)

Por isso, gostaríamos de indicar que estes campo se tornassem opcionais e não obrigatórios.

Obs.: Sobre o campo Disclaimer, o conceito está pouco descrito na documentação, mas pelo que nos passa, não parece ser um dado obrigatório na entidade de Menus, por isso incluímos dentro desta mesma Issue.

Obrigado!

**Comment by gui-camargo** [comment]
Olá @Gregcjni ,

Muito obrigado pelas sugestões. Vamos leva-las para conversar no comite.

Sobre as descrições dos campos, vou deixa-las mais claras na documentação. A questão do Disclaimer é justamente para uma descrição mais completa, e pode ser colocado questões como por exemplo questão da dieta (como itens veganos ou gluten-frre) ou questões alergicas, etc. Mas o texto é livre. 

Apenas para lembrar, como já fizemos o lançamento da versão 1.0.0 de cardápios e pedidos, as próximas atualizações irão entrar num cronograma de releases, a ser ainda divulgado.

**Comment by gui-camargo** [comment]
Solicitação será incluída na próxima versão.

**Comment by gui-camargo** [comment]
Olá @Gregcjni,

As obrigatoriedades foram retiradas na versão 1.0.1.
Documentação já está atualizada.
