### ISSUE TITLE
[Foody Delivery] Criação de um endpoint de eventos para entregas (e não somente hooks)

### ISSUE THREAD

**Issue by danielfoody** [Abrasel-Nacional/opendelivery#97]
A sugestão é a criação de um endpoint para os eventos das entregas do operador logístico (LOGISTICS) similar ao **GET /events:polling** que tem para os pedidos (ORDER).

Nenhum problema em implementar hooks para os eventos da entrega, de fato os hooks são a melhor opção comparado ao polling na maioria dos casos, mas o problema aqui é os eventos de tracking do entregador.

Imagine um operador logistico com 40 ou 50 mil entregadores online, sendo que cada entregador tem sua localização atualizada entre 10 e 30 segundos, agora pense nisso sendo enviado via hooks para os clients, **seria um processo bem pesado**.

Diferente dos eventos de um pedido (_criado, aceito, despachado e etc_), as mudanças da geolocation de um entregador não é uma informação que precisa de uma consistência muita rigidade durante o seu ciclo de vida. Então seria uma grande quantidade de chamadas via hooks sem necessidade, deixando a operação destes hooks bem pesada.

A melhor estratégia neste caso seria um polling, pois assim a _app-client_ que precisar da geolocation do entregador simplesmente acessa a API de polling que vai retornar sempre um evento com a última location do entregador.

Este polling também retornaria os eventos da entrega normalmente (accepted, rejected e etc), isso seria uma opção para muitos sistemas PDV que não rodam em nuvem (onde hooks não se aplica bem).

**Resumindo**, minha sugestão é que os eventos da entrega que **NÃO são de tracking** (_accepted, rejected, order_picked, etc_) estejam disponíveis tanto nos hooks quanto no polling.

E os eventos de tracking (_PICKUP_ONGOING, DELIVERY_ONGOING e RETURNING_TO_MERCHANT_) que são usados para monitorar a geolocation do entregador estariam disponíveis somente no polling onde cada _app-client_ consultaria este endpoint quando precisar da geolocation do entregador.

**Comment by gui-camargo** [comment]
Olá @danielfoody,

Nós tivemos uma discussão sobre esse tema durante os comites de definições e nesta primeira versão decidimos seguir apenas com a solução do webhook. Mas esta proposta foi levantada e colocamos no backlog do projeto.

Sobre os eventos do tracking "em andamento", fica a cargo de cada empresa combinar a frequencia ao qual ela conseguirá enviar essas informações, então é possivel flexibilizar a quantidade de envios, mas compreendo que pode ser uma coisa não escalável para operações grandes.

Há também uma maneira do Logistic Service enviar uma URL especifica de algum serviço da empresa para que o solicitante acompanhe a entrega em "real time". Esse campo é o `externalTrackingURL`.

Então neste primeiro momento vamos manter apenas o webhook, mas já com o polling mapeado para uma próxima versão da API. 


Então para este primeiro momento vamos seguir com o webhook e nas próximas versões iniciaremos as discussões sobre novos endpoints.

**Comment by gui-camargo** [comment]
Solicitação incluída no backlog. Necessário priorização para inclusão nas próximas versões.
