### ISSUE TITLE
[Hub Delivery] Merchant Update - Envio de endpoint e API Key do merchant

### ISSUE THREAD

**Issue by hubdelivery** [Abrasel-Nacional/opendelivery#98]
[Hub Delivery] Merchant Update - Envio de endpoint e API Key do merchant

Sugiremos que seja adicionada dois novos headers (Endpoint e ApiKey) contendo as informações do endpoint para consulta do merchant no softwarte service e o ApiKey a ser utilizado nesta consulta.

Essa mudança irá deixar mais flexível a consulta de merchants e não dependerá de uma configuração inicial ou alterações futuras no canal de vendas.

**Comment by gui-camargo** [comment]
Olá @hubdelivery,

Estamos pensando em algumas maneiras de facilitar a troca de informações e o onboarding dos softwares. 
Para esclarecer, em qual rota este header poderia ser adicionado?

De qualquer maneira, vamos tratar esse assunto no próximo comite.

**Comment by hubdelivery** [comment]
@gui-camargo, a sugestão é que os headers poderiam ser adicionadas na rota de merchant update

![image](https://user-images.githubusercontent.com/91287812/169843692-c9b8782e-b97c-4517-bac5-5b5e4a63ee8f.png)

**Comment by gui-camargo** [comment]
Olá @hubdelivery,

O endpoint PUT /v1/merchantOnboarding foi incluido na versão 1.0.1.

Documentação já atualizada.
