### ISSUE TITLE
[e-Deploy] Typos nas APIs de Logística

### ISSUE THREAD

**Issue by eduardoalmeida** [Abrasel-Nacional/opendelivery#99]
Na API de "Request new delivery" no campo vehicle.containerSize o valor "EXTRA LARGE" está sem o "_" que é padrão nos campos que tem duas palavras.

Na api "Tracking event webhook" o campo deliveryPrice.pricingList o "DINAMIC" deveria ser "DYNAMIC".

Na api "Tracking event webhook" o campo event.type nos valores tem "ARRIVED_AT_COSTUMER", deveria ser "ARRIVED_AT_CUSTUMER". O valor "RETURNING_TO MERCHANT" está sem a última "_"

Na API de "Request new delivery" o objeto vehicle possuí o campo containerSize mas na api "Tracking event webhook" o objeto vehicle não possuí esse campo.

**Comment by gui-camargo** [comment]
Olá @eduardoalmeida,

Os typos foram arrumados e os campos corrigidos.
Já dísponível na versão Beta.
